-- =================================================================
-- Schema bootstrap: tables, indexes, staging, monitoring views.
-- =================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'flashback') THEN
        EXECUTE 'CREATE SCHEMA flashback';
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('flashback.delta_log') IS NULL THEN
        -- Partitioned table: PARTITION BY RANGE (committed_at).
        -- Partition pruning in restore queries requires committed_at in WHERE clauses.
        -- PK is (committed_at, event_id) because partition key must be in PK.
        EXECUTE 'CREATE TABLE flashback.delta_log (
            event_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
            event_time      TIMESTAMPTZ NOT NULL DEFAULT now(),
            rel_oid         OID,
            tracking_id     BIGINT,
            generation_id   BIGINT,
            stream_id       BIGINT,
            source_xid      BIGINT,
            committed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            schema_version  BIGINT NOT NULL DEFAULT 1,
            event_type      TEXT NOT NULL,
            table_name      TEXT NOT NULL,
            old_data        JSONB,
            new_data        JSONB,
            ddl_info        JSONB,
            lsn             PG_LSN,
            commit_lsn      PG_LSN,
            PRIMARY KEY (committed_at, event_id)
        ) PARTITION BY RANGE (committed_at)';
        -- Default partition captures data that doesn''t match any range partition
        EXECUTE 'CREATE TABLE flashback.delta_log_default PARTITION OF flashback.delta_log DEFAULT';
    END IF;
END
$$;

-- Enable lz4 compression on JSONB columns for storage efficiency.
-- Silently skips if server was not built with lz4 support.
DO $$
BEGIN
    IF to_regclass('flashback.delta_log') IS NOT NULL THEN
        BEGIN
            ALTER TABLE flashback.delta_log ALTER COLUMN old_data SET COMPRESSION lz4;
            ALTER TABLE flashback.delta_log ALTER COLUMN new_data SET COMPRESSION lz4;
        EXCEPTION WHEN feature_not_supported THEN
            RAISE NOTICE 'pg_flashback: lz4 compression not available, using default compression for delta_log';
        END;
    END IF;
END
$$;

-- Coverage payload-binding scaffold. These columns remain nullable until the
-- generation runtime is wired atomically. `lsn` is the row-change LSN;
-- `commit_lsn` is the transaction COMMIT LSN used for visibility/watermarks.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'delta_log'
          AND column_name = 'tracking_id'
    ) THEN
        ALTER TABLE flashback.delta_log ADD COLUMN tracking_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'delta_log'
          AND column_name = 'generation_id'
    ) THEN
        ALTER TABLE flashback.delta_log ADD COLUMN generation_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'delta_log'
          AND column_name = 'stream_id'
    ) THEN
        ALTER TABLE flashback.delta_log ADD COLUMN stream_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'delta_log'
          AND column_name = 'commit_lsn'
    ) THEN
        ALTER TABLE flashback.delta_log ADD COLUMN commit_lsn PG_LSN;
    END IF;
END
$$;

CREATE SEQUENCE IF NOT EXISTS flashback.tracking_id_seq;

-- Immutable owner of one track -> untrack lifecycle.  `tracked_tables` below
-- is only the current physical binding; historical generations and incidents
-- must not depend on that mutable/deletable row for referential integrity.
CREATE TABLE IF NOT EXISTS flashback.tracking_lifecycles (
    tracking_id          BIGINT PRIMARY KEY
                         DEFAULT nextval('flashback.tracking_id_seq'),
    recovery_profile     TEXT NOT NULL
                         CHECK (recovery_profile IN ('local_delta', 'backup')),
    initial_rel_oid      OID NOT NULL,
    initial_schema_name  TEXT NOT NULL CHECK (btrim(initial_schema_name) <> ''),
    initial_table_name   TEXT NOT NULL CHECK (btrim(initial_table_name) <> ''),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    created_by           NAME NOT NULL DEFAULT current_user,
    retired_at           TIMESTAMPTZ,
    retired_by           NAME,
    retirement_reason    TEXT,
    retired_rel_oid      OID,
    retired_schema_name  TEXT,
    retired_table_name   TEXT,
    details              JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT tracking_lifecycles_tracking_profile_key
        UNIQUE (tracking_id, recovery_profile),
    CONSTRAINT tracking_lifecycles_retirement_shape_check CHECK (
        (
            retired_at IS NULL
            AND retired_by IS NULL
            AND retirement_reason IS NULL
            AND retired_rel_oid IS NULL
            AND retired_schema_name IS NULL
            AND retired_table_name IS NULL
        ) OR (
            retired_at IS NOT NULL
            AND retired_by IS NOT NULL
            AND retirement_reason IS NOT NULL
            AND btrim(retirement_reason) <> ''
            AND retired_rel_oid IS NOT NULL
            AND retired_schema_name IS NOT NULL
            AND btrim(retired_schema_name) <> ''
            AND retired_table_name IS NOT NULL
            AND btrim(retired_table_name) <> ''
        )
    )
);

CREATE OR REPLACE FUNCTION flashback_guard_tracking_lifecycle_immutable()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, flashback
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'pg_flashback: tracking lifecycle % is immutable', OLD.tracking_id
            USING ERRCODE = 'integrity_constraint_violation',
                  HINT = 'Retire the lifecycle by removing its current tracked_tables binding; do not delete its audit row.';
    END IF;

    IF NEW.tracking_id IS DISTINCT FROM OLD.tracking_id
       OR NEW.recovery_profile IS DISTINCT FROM OLD.recovery_profile
       OR NEW.initial_rel_oid IS DISTINCT FROM OLD.initial_rel_oid
       OR NEW.initial_schema_name IS DISTINCT FROM OLD.initial_schema_name
       OR NEW.initial_table_name IS DISTINCT FROM OLD.initial_table_name
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
       OR NEW.created_by IS DISTINCT FROM OLD.created_by
       OR NEW.details IS DISTINCT FROM OLD.details
    THEN
        RAISE EXCEPTION 'pg_flashback: immutable identity fields of tracking lifecycle % cannot change', OLD.tracking_id
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.retired_at IS NOT NULL THEN
        IF NEW IS DISTINCT FROM OLD THEN
            RAISE EXCEPTION 'pg_flashback: retired tracking lifecycle % cannot change', OLD.tracking_id
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.retired_at IS NULL THEN
        IF NEW.retired_by IS DISTINCT FROM OLD.retired_by
           OR NEW.retirement_reason IS DISTINCT FROM OLD.retirement_reason
           OR NEW.retired_rel_oid IS DISTINCT FROM OLD.retired_rel_oid
           OR NEW.retired_schema_name IS DISTINCT FROM OLD.retired_schema_name
           OR NEW.retired_table_name IS DISTINCT FROM OLD.retired_table_name
        THEN
            RAISE EXCEPTION 'pg_flashback: lifecycle % retirement fields must be written atomically', OLD.tracking_id
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        RETURN NEW;
    END IF;

    IF EXISTS (
        SELECT 1 FROM flashback.tracked_tables tt
        WHERE tt.tracking_id = OLD.tracking_id
    ) THEN
        RAISE EXCEPTION 'pg_flashback: lifecycle % still has a current table binding', OLD.tracking_id
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tracking_lifecycles_immutable
    ON flashback.tracking_lifecycles;
CREATE TRIGGER tracking_lifecycles_immutable
BEFORE UPDATE OR DELETE ON flashback.tracking_lifecycles
FOR EACH ROW EXECUTE FUNCTION flashback_guard_tracking_lifecycle_immutable();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'delta_log' AND column_name = 'source_xid'
    ) THEN
        ALTER TABLE flashback.delta_log ADD COLUMN source_xid BIGINT;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'delta_log' AND column_name = 'lsn'
    ) THEN
        ALTER TABLE flashback.delta_log ADD COLUMN lsn PG_LSN;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'delta_log' AND column_name = 'committed_at'
    ) THEN
        ALTER TABLE flashback.delta_log ADD COLUMN committed_at TIMESTAMPTZ;
    END IF;

    UPDATE flashback.delta_log
    SET committed_at = COALESCE(committed_at, event_time)
    WHERE committed_at IS NULL;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'delta_log' AND column_name = 'rel_oid'
    ) THEN
        ALTER TABLE flashback.delta_log ADD COLUMN rel_oid OID;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'delta_log' AND column_name = 'ddl_info'
    ) THEN
        ALTER TABLE flashback.delta_log ADD COLUMN ddl_info JSONB;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'delta_log' AND column_name = 'schema_version'
    ) THEN
        ALTER TABLE flashback.delta_log ADD COLUMN schema_version BIGINT NOT NULL DEFAULT 1;
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('flashback.tracked_tables') IS NULL THEN
        EXECUTE 'CREATE TABLE flashback.tracked_tables (
            tracking_id          BIGINT NOT NULL DEFAULT nextval(''flashback.tracking_id_seq''),
            rel_oid              OID PRIMARY KEY,
            schema_name          TEXT NOT NULL,
            table_name           TEXT NOT NULL,
            base_snapshot_table  TEXT,
            schema_version       BIGINT NOT NULL DEFAULT 1,
            recovery_profile     TEXT NOT NULL DEFAULT ''local_delta'',
            helper_profile       TEXT,
            coverage_start_lsn   PG_LSN,
            coverage_end_lsn     PG_LSN,
            tracked_since        TIMESTAMPTZ NOT NULL DEFAULT now(),
            checkpoint_interval  INTERVAL NOT NULL DEFAULT interval ''15 minutes'',
            retention_interval   INTERVAL NOT NULL DEFAULT interval ''7 days'',
            is_active            BOOLEAN NOT NULL DEFAULT true,
            CONSTRAINT tracked_tables_tracking_id_key UNIQUE (tracking_id),
            CONSTRAINT tracked_tables_tracking_profile_key
                UNIQUE (tracking_id, recovery_profile),
            UNIQUE(schema_name, table_name)
        )';
    END IF;
END
$$;

-- A stable tracking identity survives shadow-table swaps that replace rel_oid.
-- Existing rows receive an identity, but no coverage generation is fabricated:
-- legacy boundaries were not established by the exact-boundary protocol.
DO $$
DECLARE
    v_max_tracking_id bigint;
    v_sequence_last bigint;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables'
          AND column_name = 'tracking_id'
    ) THEN
        ALTER TABLE flashback.tracked_tables ADD COLUMN tracking_id BIGINT;
    END IF;

    ALTER TABLE flashback.tracked_tables
        ALTER COLUMN tracking_id SET DEFAULT nextval('flashback.tracking_id_seq');
    UPDATE flashback.tracked_tables
       SET tracking_id = nextval('flashback.tracking_id_seq')
     WHERE tracking_id IS NULL;
    ALTER TABLE flashback.tracked_tables ALTER COLUMN tracking_id SET NOT NULL;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.tracked_tables'::regclass
          AND conname = 'tracked_tables_tracking_id_key'
    ) THEN
        ALTER TABLE flashback.tracked_tables
            ADD CONSTRAINT tracked_tables_tracking_id_key UNIQUE (tracking_id);
    END IF;

    SELECT max(tracking_id) INTO v_max_tracking_id
    FROM flashback.tracked_tables;
    IF v_max_tracking_id IS NOT NULL THEN
        SELECT last_value INTO v_sequence_last
        FROM flashback.tracking_id_seq;
        PERFORM setval(
            'flashback.tracking_id_seq',
            GREATEST(v_max_tracking_id, v_sequence_last),
            true
        );
    END IF;
END
$$;

DO $$
BEGIN
    ALTER TABLE flashback.tracked_tables ALTER COLUMN base_snapshot_table DROP NOT NULL;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables'
          AND column_name = 'recovery_profile'
    ) THEN
        ALTER TABLE flashback.tracked_tables
            ADD COLUMN recovery_profile TEXT NOT NULL DEFAULT 'local_delta';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables'
          AND column_name = 'helper_profile'
    ) THEN
        ALTER TABLE flashback.tracked_tables ADD COLUMN helper_profile TEXT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables'
          AND column_name = 'coverage_start_lsn'
    ) THEN
        ALTER TABLE flashback.tracked_tables ADD COLUMN coverage_start_lsn PG_LSN;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables'
          AND column_name = 'coverage_end_lsn'
    ) THEN
        ALTER TABLE flashback.tracked_tables ADD COLUMN coverage_end_lsn PG_LSN;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.tracked_tables'::regclass
          AND conname = 'tracked_tables_recovery_profile_check'
    ) THEN
        ALTER TABLE flashback.tracked_tables
            ADD CONSTRAINT tracked_tables_recovery_profile_check
            CHECK (recovery_profile IN ('local_delta', 'backup'));
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.tracked_tables'::regclass
          AND conname = 'tracked_tables_tracking_profile_key'
    ) THEN
        ALTER TABLE flashback.tracked_tables
            ADD CONSTRAINT tracked_tables_tracking_profile_key
            UNIQUE (tracking_id, recovery_profile);
    END IF;
END
$$;

-- Migrate every current binding to an immutable lifecycle parent.  This does
-- not create a coverage generation or claim that a legacy boundary is valid.
INSERT INTO flashback.tracking_lifecycles (
    tracking_id, recovery_profile, initial_rel_oid,
    initial_schema_name, initial_table_name, created_at, created_by
)
SELECT
    tt.tracking_id, tt.recovery_profile, tt.rel_oid,
    tt.schema_name, tt.table_name, tt.tracked_since, current_user
FROM flashback.tracked_tables tt
ON CONFLICT (tracking_id) DO NOTHING;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM flashback.tracked_tables tt
        JOIN flashback.tracking_lifecycles tl USING (tracking_id)
        WHERE tl.recovery_profile IS DISTINCT FROM tt.recovery_profile
    ) THEN
        RAISE EXCEPTION 'pg_flashback: current table binding conflicts with immutable lifecycle profile';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.tracked_tables'::regclass
          AND conname = 'tracked_tables_lifecycle_profile_fk'
    ) THEN
        ALTER TABLE flashback.tracked_tables
            ADD CONSTRAINT tracked_tables_lifecycle_profile_fk
            FOREIGN KEY (tracking_id, recovery_profile)
            REFERENCES flashback.tracking_lifecycles(tracking_id, recovery_profile)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;

    ALTER SEQUENCE flashback.tracking_id_seq
        OWNED BY flashback.tracking_lifecycles.tracking_id;
END
$$;

-- Compatibility bridge for the legacy runtime while lifecycle-aware track is
-- wired: a direct current-binding INSERT creates exactly one parent, and an
-- UPDATE may change the physical binding but never its lifecycle/profile.
CREATE OR REPLACE FUNCTION flashback_bind_current_tracking_lifecycle()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, flashback
AS $$
DECLARE
    v_profile text;
    v_retired_at timestamptz;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.tracking_id IS DISTINCT FROM OLD.tracking_id
           OR NEW.recovery_profile IS DISTINCT FROM OLD.recovery_profile
        THEN
            RAISE EXCEPTION 'pg_flashback: a current binding cannot change lifecycle or recovery profile'
                USING ERRCODE = 'integrity_constraint_violation',
                      HINT = 'Untrack and create a new lifecycle instead.';
        END IF;
        RETURN NEW;
    END IF;

    INSERT INTO flashback.tracking_lifecycles (
        tracking_id, recovery_profile, initial_rel_oid,
        initial_schema_name, initial_table_name, created_at, created_by
    ) VALUES (
        NEW.tracking_id, NEW.recovery_profile, NEW.rel_oid,
        NEW.schema_name, NEW.table_name,
        COALESCE(NEW.tracked_since, clock_timestamp()), current_user
    )
    ON CONFLICT (tracking_id) DO NOTHING;

    SELECT recovery_profile, retired_at
      INTO v_profile, v_retired_at
    FROM flashback.tracking_lifecycles
    WHERE tracking_id = NEW.tracking_id;

    IF v_retired_at IS NOT NULL THEN
        RAISE EXCEPTION 'pg_flashback: retired lifecycle % cannot be rebound', NEW.tracking_id
            USING ERRCODE = 'integrity_constraint_violation',
                  HINT = 'Allocate a new tracking_id for the new tracking lifecycle.';
    END IF;
    IF v_profile IS DISTINCT FROM NEW.recovery_profile THEN
        RAISE EXCEPTION 'pg_flashback: lifecycle % has profile %, not %',
            NEW.tracking_id, v_profile, NEW.recovery_profile
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION flashback_guard_current_tracking_delete()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, flashback
AS $$
BEGIN
    IF to_regclass('flashback.coverage_generations') IS NOT NULL
       AND EXISTS (
           SELECT 1
           FROM flashback.coverage_generations cg
           WHERE cg.tracking_id = OLD.tracking_id
             AND cg.state IN ('building', 'active')
       )
    THEN
        RAISE EXCEPTION 'pg_flashback: lifecycle % still has an eligible or pending generation', OLD.tracking_id
            USING ERRCODE = 'integrity_constraint_violation',
                  HINT = 'Finalize generation retirement under the lifecycle lock before removing the current binding.';
    END IF;
    RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION flashback_retire_tracking_lifecycle()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, flashback
AS $$
BEGIN
    UPDATE flashback.tracking_lifecycles
       SET retired_at = clock_timestamp(),
           retired_by = current_user,
           retirement_reason = 'current_binding_removed',
           retired_rel_oid = OLD.rel_oid,
           retired_schema_name = OLD.schema_name,
           retired_table_name = OLD.table_name
     WHERE tracking_id = OLD.tracking_id
       AND retired_at IS NULL;
    RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS tracked_tables_bind_lifecycle
    ON flashback.tracked_tables;
CREATE TRIGGER tracked_tables_bind_lifecycle
BEFORE INSERT OR UPDATE ON flashback.tracked_tables
FOR EACH ROW EXECUTE FUNCTION flashback_bind_current_tracking_lifecycle();

DROP TRIGGER IF EXISTS tracked_tables_guard_delete
    ON flashback.tracked_tables;
CREATE TRIGGER tracked_tables_guard_delete
BEFORE DELETE ON flashback.tracked_tables
FOR EACH ROW EXECUTE FUNCTION flashback_guard_current_tracking_delete();

DROP TRIGGER IF EXISTS tracked_tables_retire_lifecycle
    ON flashback.tracked_tables;
CREATE TRIGGER tracked_tables_retire_lifecycle
AFTER DELETE ON flashback.tracked_tables
FOR EACH ROW EXECUTE FUNCTION flashback_retire_tracking_lifecycle();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables' AND column_name = 'schema_version'
    ) THEN
        ALTER TABLE flashback.tracked_tables ADD COLUMN schema_version BIGINT NOT NULL DEFAULT 1;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables' AND column_name = 'retention_interval'
    ) THEN
        ALTER TABLE flashback.tracked_tables ADD COLUMN retention_interval INTERVAL NOT NULL DEFAULT interval '7 days';
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables' AND column_name = 'checkpoint_interval'
    ) THEN
        ALTER TABLE flashback.tracked_tables ADD COLUMN checkpoint_interval INTERVAL NOT NULL DEFAULT interval '15 minutes';
    END IF;
END
$$;

-- Store the table's original REPLICA IDENTITY so flashback_untrack() can restore it.
-- 'd' = DEFAULT (primary key), 'f' = FULL, 'i' = INDEX, 'n' = NOTHING.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables'
          AND column_name = 'replica_identity_was'
    ) THEN
        ALTER TABLE flashback.tracked_tables ADD COLUMN replica_identity_was "char" NOT NULL DEFAULT 'd';
    END IF;
END
$$;

-- When the original REPLICA IDENTITY was USING INDEX, store the index name here
-- so flashback_untrack() can restore it exactly. NULL when not applicable.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables'
          AND column_name = 'replica_identity_index'
    ) THEN
        ALTER TABLE flashback.tracked_tables ADD COLUMN replica_identity_index text;
    END IF;

    -- retention_cutoff: latest timestamp up to which retention has deleted events.
    -- flashback_restore raises an error if target_time < retention_cutoff.
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'tracked_tables'
          AND column_name = 'retention_cutoff'
    ) THEN
        ALTER TABLE flashback.tracked_tables ADD COLUMN retention_cutoff TIMESTAMPTZ;
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('flashback.snapshots') IS NULL THEN
        EXECUTE 'CREATE TABLE flashback.snapshots (
            snapshot_id    BIGSERIAL PRIMARY KEY,
            rel_oid        OID NOT NULL,
            tracking_id    BIGINT,
            snapshot_table TEXT NOT NULL,
            snapshot_lsn   PG_LSN NOT NULL,
            schema_def     JSONB NOT NULL,
            row_count      BIGINT NOT NULL,
            captured_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            payload_state  TEXT NOT NULL DEFAULT ''available'',
            retired_at     TIMESTAMPTZ,
            CONSTRAINT snapshots_payload_state_check
                CHECK (payload_state IN (''available'', ''retired'', ''missing'')),
            CONSTRAINT snapshots_payload_state_shape_check
                CHECK (
                    (payload_state = ''available'' AND retired_at IS NULL)
                    OR (payload_state IN (''retired'', ''missing'') AND retired_at IS NOT NULL)
                ),
            CONSTRAINT snapshots_snapshot_tracking_key UNIQUE (snapshot_id, tracking_id),
            CONSTRAINT snapshots_snapshot_tracking_lsn_key
                UNIQUE (snapshot_id, tracking_id, snapshot_lsn)
        )';
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('flashback.schema_versions') IS NULL THEN
        EXECUTE 'CREATE TABLE flashback.schema_versions (
            version_id      BIGSERIAL PRIMARY KEY,
            rel_oid         OID NOT NULL,
            tracking_id     BIGINT,
            generation_id   BIGINT,
            stream_id       BIGINT,
            source_xid      BIGINT,
            schema_version  BIGINT NOT NULL,
            applied_at      TIMESTAMPTZ NOT NULL,
            applied_lsn     PG_LSN NOT NULL,
            committed_at    TIMESTAMPTZ,
            commit_lsn      PG_LSN,
            columns         JSONB NOT NULL,
            primary_key     JSONB NOT NULL DEFAULT ''[]''::jsonb,
            constraints     JSONB NOT NULL DEFAULT ''{}''::jsonb,
            helper_schema_sha256 TEXT,
            UNIQUE(rel_oid, schema_version)
        )';
    END IF;
END
$$;

-- Stable-identity bindings remain nullable until runtime wiring. Existing
-- snapshot/schema rows are legacy evidence and are not assigned a fabricated
-- coverage generation.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'snapshots'
          AND column_name = 'tracking_id'
    ) THEN
        ALTER TABLE flashback.snapshots ADD COLUMN tracking_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'snapshots'
          AND column_name = 'payload_state'
    ) THEN
        ALTER TABLE flashback.snapshots
            ADD COLUMN payload_state TEXT NOT NULL DEFAULT 'available';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'snapshots'
          AND column_name = 'retired_at'
    ) THEN
        ALTER TABLE flashback.snapshots ADD COLUMN retired_at TIMESTAMPTZ;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'schema_versions'
          AND column_name = 'tracking_id'
    ) THEN
        ALTER TABLE flashback.schema_versions ADD COLUMN tracking_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'schema_versions'
          AND column_name = 'generation_id'
    ) THEN
        ALTER TABLE flashback.schema_versions ADD COLUMN generation_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'schema_versions'
          AND column_name = 'stream_id'
    ) THEN
        ALTER TABLE flashback.schema_versions ADD COLUMN stream_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'schema_versions'
          AND column_name = 'source_xid'
    ) THEN
        ALTER TABLE flashback.schema_versions ADD COLUMN source_xid BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'schema_versions'
          AND column_name = 'committed_at'
    ) THEN
        ALTER TABLE flashback.schema_versions ADD COLUMN committed_at TIMESTAMPTZ;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'schema_versions'
          AND column_name = 'commit_lsn'
    ) THEN
        ALTER TABLE flashback.schema_versions ADD COLUMN commit_lsn PG_LSN;
    END IF;

    -- Legacy snapshot ownership stays NULL. An OID may have been recycled
    -- after DROP/recreate, so rel_oid equality is not proof of stable tracking
    -- ownership. Only the exact-boundary runtime may populate tracking_id.

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.snapshots'::regclass
          AND conname = 'snapshots_payload_state_check'
    ) THEN
        ALTER TABLE flashback.snapshots
            ADD CONSTRAINT snapshots_payload_state_check
            CHECK (payload_state IN ('available', 'retired', 'missing'));
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.snapshots'::regclass
          AND conname = 'snapshots_payload_state_shape_check'
    ) THEN
        ALTER TABLE flashback.snapshots
            ADD CONSTRAINT snapshots_payload_state_shape_check
            CHECK (
                (payload_state = 'available' AND retired_at IS NULL)
                OR (payload_state IN ('retired', 'missing') AND retired_at IS NOT NULL)
            );
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.snapshots'::regclass
          AND conname = 'snapshots_snapshot_tracking_key'
    ) THEN
        ALTER TABLE flashback.snapshots
            ADD CONSTRAINT snapshots_snapshot_tracking_key
            UNIQUE (snapshot_id, tracking_id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.snapshots'::regclass
          AND conname = 'snapshots_snapshot_tracking_lsn_key'
    ) THEN
        ALTER TABLE flashback.snapshots
            ADD CONSTRAINT snapshots_snapshot_tracking_lsn_key
            UNIQUE (snapshot_id, tracking_id, snapshot_lsn);
    END IF;
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.snapshots'::regclass
          AND conname = 'snapshots_tracking_fk'
          AND confrelid <> 'flashback.tracking_lifecycles'::regclass
    ) THEN
        ALTER TABLE flashback.snapshots
            DROP CONSTRAINT snapshots_tracking_fk;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.snapshots'::regclass
          AND conname = 'snapshots_tracking_fk'
    ) THEN
        ALTER TABLE flashback.snapshots
            ADD CONSTRAINT snapshots_tracking_fk
            FOREIGN KEY (tracking_id)
            REFERENCES flashback.tracking_lifecycles(tracking_id)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
END
$$;

-- One database-wide capture incarnation. A WAL slot recreation or capture
-- configuration discontinuity creates a new epoch rather than silently
-- continuing an old watermark.
CREATE TABLE IF NOT EXISTS flashback.capture_streams (
    stream_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    database_oid           OID NOT NULL,
    database_name          NAME NOT NULL,
    epoch_no               BIGINT NOT NULL CHECK (epoch_no > 0),
    capture_mode           TEXT NOT NULL CHECK (capture_mode IN ('trigger', 'wal')),
    timeline_id            BIGINT CHECK (timeline_id IS NULL OR timeline_id > 0),
    slot_name              TEXT,
    plugin_name            TEXT,
    state                  TEXT NOT NULL DEFAULT 'initializing'
                           CHECK (state IN ('initializing', 'active', 'broken', 'retired')),
    valid_through_time     TIMESTAMPTZ,
    valid_through_lsn      PG_LSN,
    confirmed_flush_lsn    PG_LSN,
    restart_lsn            PG_LSN,
    invalidation_reason    TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    activated_at           TIMESTAMPTZ,
    invalidated_at         TIMESTAMPTZ,
    retired_at             TIMESTAMPTZ,
    details                JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT capture_streams_database_epoch_key UNIQUE (database_oid, epoch_no),
    CONSTRAINT capture_streams_slot_shape_check CHECK (
        (
            capture_mode = 'wal'
            AND timeline_id IS NOT NULL
            AND slot_name IS NOT NULL AND btrim(slot_name) <> ''
            AND plugin_name IS NOT NULL AND btrim(plugin_name) <> ''
        ) OR (
            capture_mode = 'trigger'
            AND timeline_id IS NULL
            AND slot_name IS NULL
            AND plugin_name IS NULL
        )
    ),
    CONSTRAINT capture_streams_state_shape_check CHECK (
        (state = 'initializing' AND invalidated_at IS NULL AND retired_at IS NULL)
        OR (
            state = 'active'
            AND activated_at IS NOT NULL
            AND invalidated_at IS NULL
            AND retired_at IS NULL
        )
        OR (
            state = 'broken'
            AND invalidated_at IS NOT NULL
            AND invalidation_reason IS NOT NULL
            AND btrim(invalidation_reason) <> ''
            AND retired_at IS NULL
        )
        OR (state = 'retired' AND retired_at IS NOT NULL)
    )
);

-- Durable COMMIT-order ledger for one logical-decoding stream.  delta_log
-- stores only changes relevant to tracked tables; timestamp-to-LSN planning
-- needs the complete observed transaction prefix so it can prove that a wall
-- clock cut is also a real WAL prefix (and reject clock inversions otherwise).
CREATE TABLE IF NOT EXISTS flashback.capture_commits (
    stream_id      BIGINT NOT NULL,
    commit_lsn     PG_LSN NOT NULL,
    source_xid     BIGINT NOT NULL,
    committed_at   TIMESTAMPTZ NOT NULL,
    observed_at    TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (stream_id, commit_lsn),
    CONSTRAINT capture_commits_stream_fk
        FOREIGN KEY (stream_id)
        REFERENCES flashback.capture_streams(stream_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS capture_commits_stream_time_lsn_idx
    ON flashback.capture_commits (stream_id, committed_at, commit_lsn);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'capture_streams'
          AND column_name = 'timeline_id'
    ) THEN
        ALTER TABLE flashback.capture_streams ADD COLUMN timeline_id BIGINT;
    END IF;
    ALTER TABLE flashback.capture_streams
        DROP CONSTRAINT IF EXISTS capture_streams_slot_shape_check;
    ALTER TABLE flashback.capture_streams
        ADD CONSTRAINT capture_streams_slot_shape_check CHECK (
            (
                capture_mode = 'wal'
                AND timeline_id IS NOT NULL AND timeline_id > 0
                AND slot_name IS NOT NULL AND btrim(slot_name) <> ''
                AND plugin_name IS NOT NULL AND btrim(plugin_name) <> ''
            ) OR (
                capture_mode = 'trigger'
                AND timeline_id IS NULL
                AND slot_name IS NULL
                AND plugin_name IS NULL
            )
        );
END
$$;

-- Immutable proof that one backup-profile generation is anchored by one
-- concrete, verified pgBackRest FULL backup.  A profile name alone is not
-- evidence: admission must pin repository/stanza/label, cluster identity,
-- timeline, manifest digest and physical WAL coordinates together.
CREATE TABLE IF NOT EXISTS flashback.backup_anchors (
    backup_anchor_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id                BIGINT NOT NULL,
    helper_profile             TEXT NOT NULL CHECK (btrim(helper_profile) <> ''),
    repository_key             TEXT NOT NULL CHECK (btrim(repository_key) <> ''),
    stanza                     TEXT NOT NULL CHECK (btrim(stanza) <> ''),
    backup_label               TEXT NOT NULL CHECK (btrim(backup_label) <> ''),
    backup_type                TEXT NOT NULL CHECK (backup_type = 'full'),
    database_system_identifier NUMERIC(20, 0) NOT NULL
                               CHECK (database_system_identifier > 0),
    timeline_id                BIGINT NOT NULL CHECK (timeline_id > 0),
    manifest_reference         TEXT NOT NULL CHECK (btrim(manifest_reference) <> ''),
    manifest_sha256            TEXT NOT NULL
                               CHECK (manifest_sha256 ~ '^[0-9a-f]{64}$'),
    -- pgBackRest obtains the backup start LSN only after its backup-start
    -- checkpoint. It must be strictly after the durable lifecycle marker.
    -- This rejects a pre-track or swap-overlapping backup.
    tracking_marker_lsn        PG_LSN NOT NULL,
    backup_start_lsn           PG_LSN NOT NULL,
    backup_stop_lsn            PG_LSN NOT NULL,
    verified_at                TIMESTAMPTZ NOT NULL,
    verified_by                NAME NOT NULL DEFAULT current_user,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    details                    JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT backup_anchors_tracking_fk
        FOREIGN KEY (tracking_id)
        REFERENCES flashback.tracking_lifecycles(tracking_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT backup_anchors_identity_key
        UNIQUE (
            tracking_id, repository_key, stanza, backup_label,
            database_system_identifier, timeline_id
        ),
    CONSTRAINT backup_anchors_anchor_tracking_stop_key
        UNIQUE (backup_anchor_id, tracking_id, backup_stop_lsn),
    CONSTRAINT backup_anchors_after_marker_check CHECK (
        backup_start_lsn > tracking_marker_lsn
    ),
    CONSTRAINT backup_anchors_stop_order_check CHECK (
        backup_stop_lsn >= backup_start_lsn
    )
);

-- One-time verified coverage proofs. Only the recovery agent (or a superuser
-- installing on behalf of a locked helper verification) may insert rows.
-- flashback_admin cannot forge coverage by supplying raw LSNs/manifests.
CREATE TABLE IF NOT EXISTS flashback.verified_backup_proofs (
    proof_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verification_request_id      TEXT NOT NULL CHECK (btrim(verification_request_id) <> ''),
    tracking_id                  BIGINT NOT NULL,
    helper_profile               TEXT NOT NULL CHECK (btrim(helper_profile) <> ''),
    repository_key               TEXT NOT NULL CHECK (btrim(repository_key) <> ''),
    stanza                       TEXT NOT NULL CHECK (btrim(stanza) <> ''),
    backup_label                 TEXT NOT NULL CHECK (btrim(backup_label) <> ''),
    backup_type                  TEXT NOT NULL CHECK (backup_type = 'full'),
    database_system_identifier   NUMERIC(20, 0) NOT NULL CHECK (database_system_identifier > 0),
    timeline_id                  BIGINT NOT NULL CHECK (timeline_id > 0),
    manifest_reference           TEXT NOT NULL CHECK (btrim(manifest_reference) <> ''),
    manifest_sha256              TEXT NOT NULL CHECK (manifest_sha256 ~ '^[0-9a-f]{64}$'),
    backup_start_lsn             PG_LSN NOT NULL,
    backup_stop_lsn              PG_LSN NOT NULL,
    verified_at                  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    installed_by                 NAME NOT NULL DEFAULT session_user,
    installed_at                 TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    consumed_at                  TIMESTAMPTZ,
    consumed_generation_id       BIGINT,
    details                      JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT verified_backup_proofs_verification_key
        UNIQUE (verification_request_id),
    CONSTRAINT verified_backup_proofs_tracking_fk
        FOREIGN KEY (tracking_id)
        REFERENCES flashback.tracking_lifecycles(tracking_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT verified_backup_proofs_stop_order_check CHECK (
        backup_stop_lsn >= backup_start_lsn
    ),
    CONSTRAINT verified_backup_proofs_consume_shape_check CHECK (
        (consumed_at IS NULL AND consumed_generation_id IS NULL)
        OR (consumed_at IS NOT NULL AND consumed_generation_id IS NOT NULL)
    )
);


-- A generation is an immutable restore chain anchored by one exact boundary.
-- The nullable snapshot/stream links support backup generations and the
-- deliberately unqualified legacy state during migration.
CREATE TABLE IF NOT EXISTS flashback.coverage_generations (
    generation_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id            BIGINT NOT NULL,
    generation_no          BIGINT NOT NULL CHECK (generation_no > 0),
    parent_generation_id   BIGINT,
    stream_id              BIGINT,
    recovery_profile       TEXT NOT NULL
                           CHECK (recovery_profile IN ('local_delta', 'backup')),
    state                  TEXT NOT NULL DEFAULT 'building'
                           CHECK (state IN ('building', 'active', 'sealed', 'retired', 'aborted')),
    boundary_kind          TEXT NOT NULL CHECK (btrim(boundary_kind) <> ''),
    rel_oid_at_boundary    OID NOT NULL,
    boundary_snapshot_id   BIGINT,
    backup_anchor_id       BIGINT,
    canonical_coordinate_kind TEXT GENERATED ALWAYS AS (
        CASE recovery_profile
            WHEN 'local_delta' THEN 'commit_lsn'
            WHEN 'backup' THEN 'physical_lsn'
        END
    ) STORED,
    -- A transaction cannot know its own commit time/COMMIT LSN. A building
    -- generation therefore carries a pending XID/marker until a later
    -- qualification step resolves the exact boundary coordinates.
    boundary_xid           BIGINT,
    boundary_marker        TEXT CHECK (boundary_marker IS NULL OR btrim(boundary_marker) <> ''),
    boundary_time          TIMESTAMPTZ,
    boundary_lsn           PG_LSN,
    valid_through_time     TIMESTAMPTZ,
    valid_through_lsn      PG_LSN,
    -- Exclusive upper applicability bound. Capture completeness remains in
    -- valid_through_*; these fields say when a successor generation takes over.
    superseded_before_time TIMESTAMPTZ,
    superseded_before_lsn  PG_LSN,
    restored_target_time   TIMESTAMPTZ,
    restored_target_lsn    PG_LSN,
    activated_at           TIMESTAMPTZ,
    sealed_at              TIMESTAMPTZ,
    retired_at             TIMESTAMPTZ,
    aborted_at             TIMESTAMPTZ,
    state_reason           TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    details                JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT coverage_generations_tracking_number_key
        UNIQUE (tracking_id, generation_no),
    CONSTRAINT coverage_generations_generation_tracking_key
        UNIQUE (generation_id, tracking_id),
    CONSTRAINT coverage_generations_generation_tracking_stream_key
        UNIQUE (generation_id, tracking_id, stream_id),
    CONSTRAINT coverage_generations_tracking_profile_fk
        FOREIGN KEY (tracking_id, recovery_profile)
        REFERENCES flashback.tracking_lifecycles(tracking_id, recovery_profile)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT coverage_generations_parent_tracking_fk
        FOREIGN KEY (parent_generation_id, tracking_id)
        REFERENCES flashback.coverage_generations(generation_id, tracking_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT coverage_generations_stream_fk
        FOREIGN KEY (stream_id)
        REFERENCES flashback.capture_streams(stream_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT coverage_generations_boundary_snapshot_tracking_fk
        FOREIGN KEY (boundary_snapshot_id, tracking_id, boundary_lsn)
        REFERENCES flashback.snapshots(snapshot_id, tracking_id, snapshot_lsn)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT coverage_generations_backup_anchor_tracking_lsn_fk
        FOREIGN KEY (backup_anchor_id, tracking_id, boundary_lsn)
        REFERENCES flashback.backup_anchors(
            backup_anchor_id, tracking_id, backup_stop_lsn
        )
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT coverage_generations_lsn_order_check
        CHECK (valid_through_lsn IS NULL OR boundary_lsn IS NULL
               OR valid_through_lsn >= boundary_lsn),
    CONSTRAINT coverage_generations_superseded_lsn_order_check
        CHECK (superseded_before_lsn IS NULL OR boundary_lsn IS NULL
               OR superseded_before_lsn > boundary_lsn),
    CONSTRAINT coverage_generations_watermark_applicability_lsn_check
        CHECK (valid_through_lsn IS NULL OR superseded_before_lsn IS NULL
               OR valid_through_lsn <= superseded_before_lsn),
    CONSTRAINT coverage_generations_profile_shape_check CHECK (
        (
            recovery_profile = 'local_delta'
            AND stream_id IS NOT NULL
            AND boundary_snapshot_id IS NOT NULL
            AND backup_anchor_id IS NULL
        ) OR (
            recovery_profile = 'backup'
            AND stream_id IS NULL
            AND boundary_snapshot_id IS NULL
            AND (
                state IN ('building', 'aborted')
                OR (
                    backup_anchor_id IS NOT NULL
                    AND boundary_lsn IS NOT NULL
                    AND valid_through_lsn IS NOT NULL
                )
            )
        )
    ),
    CONSTRAINT coverage_generations_state_shape_check CHECK (
        (
            state = 'building'
            AND (
                (boundary_time IS NOT NULL AND boundary_lsn IS NOT NULL)
                OR boundary_xid IS NOT NULL
                OR boundary_marker IS NOT NULL
            )
        )
        OR (
            state = 'active'
            AND activated_at IS NOT NULL
            AND boundary_time IS NOT NULL
            AND boundary_lsn IS NOT NULL
            AND valid_through_lsn IS NOT NULL
        )
        OR (
            state = 'sealed'
            AND sealed_at IS NOT NULL
            AND boundary_time IS NOT NULL
            AND boundary_lsn IS NOT NULL
            AND valid_through_lsn IS NOT NULL
        )
        OR (
            state = 'retired'
            AND retired_at IS NOT NULL
            AND boundary_time IS NOT NULL
            AND boundary_lsn IS NOT NULL
            AND valid_through_lsn IS NOT NULL
        )
        OR (
            state = 'aborted'
            AND aborted_at IS NOT NULL
        )
    ),
    CONSTRAINT coverage_generations_applicability_shape_check CHECK (
        (
            state IN ('building', 'active', 'aborted')
            AND superseded_before_time IS NULL
            AND superseded_before_lsn IS NULL
        ) OR (
            state IN ('sealed', 'retired')
            AND superseded_before_lsn IS NOT NULL
        )
    )
);

CREATE TABLE IF NOT EXISTS flashback.verified_wal_frontier_proofs (
    proof_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verification_request_id      TEXT NOT NULL CHECK (btrim(verification_request_id) <> ''),
    tracking_id                  BIGINT NOT NULL,
    generation_id                BIGINT NOT NULL,
    helper_profile               TEXT NOT NULL CHECK (btrim(helper_profile) <> ''),
    repository_key               TEXT NOT NULL CHECK (btrim(repository_key) <> ''),
    stanza                       TEXT NOT NULL CHECK (btrim(stanza) <> ''),
    timeline_id                  BIGINT NOT NULL CHECK (timeline_id > 0),
    valid_through_lsn            PG_LSN NOT NULL,
    archive_proof_sha256         TEXT NOT NULL CHECK (archive_proof_sha256 ~ '^[0-9a-f]{64}$'),
    verified_at                  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    installed_by                 NAME NOT NULL DEFAULT session_user,
    installed_at                 TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    consumed_at                  TIMESTAMPTZ,
    details                      JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT verified_wal_frontier_proofs_verification_key
        UNIQUE (verification_request_id),
    CONSTRAINT verified_wal_frontier_proofs_tracking_fk
        FOREIGN KEY (tracking_id)
        REFERENCES flashback.tracking_lifecycles(tracking_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT verified_wal_frontier_proofs_generation_tracking_fk
        FOREIGN KEY (generation_id, tracking_id)
        REFERENCES flashback.coverage_generations(generation_id, tracking_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT verified_wal_frontier_proofs_consume_shape_check CHECK (
        consumed_at IS NULL OR consumed_at IS NOT NULL
    )
);

-- Permanent rejection intervals. Re-anchor fills the upper endpoint but does
-- not delete or heal the historical gap.
CREATE TABLE IF NOT EXISTS flashback.coverage_gaps (
    gap_id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id                  BIGINT NOT NULL,
    source_generation_id         BIGINT NOT NULL,
    reason                       TEXT NOT NULL CHECK (btrim(reason) <> ''),
    gap_start_time               TIMESTAMPTZ,
    gap_start_lsn                PG_LSN,
    lower_bound_inclusive        BOOLEAN NOT NULL DEFAULT false,
    source_xid                   BIGINT,
    gap_end_time                 TIMESTAMPTZ,
    gap_end_lsn                  PG_LSN,
    reanchored_by_generation_id  BIGINT,
    detected_at                  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    reanchored_at                TIMESTAMPTZ,
    details                      JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT coverage_gaps_tracking_fk
        FOREIGN KEY (tracking_id)
        REFERENCES flashback.tracking_lifecycles(tracking_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT coverage_gaps_source_tracking_fk
        FOREIGN KEY (source_generation_id, tracking_id)
        REFERENCES flashback.coverage_generations(generation_id, tracking_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT coverage_gaps_reanchor_tracking_fk
        FOREIGN KEY (reanchored_by_generation_id, tracking_id)
        REFERENCES flashback.coverage_generations(generation_id, tracking_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT coverage_gaps_start_coordinate_check CHECK (
        gap_start_time IS NOT NULL OR gap_start_lsn IS NOT NULL OR source_xid IS NOT NULL
    ),
    CONSTRAINT coverage_gaps_reanchor_shape_check CHECK (
        (
            reanchored_by_generation_id IS NULL
            AND reanchored_at IS NULL
            AND gap_end_time IS NULL
            AND gap_end_lsn IS NULL
        ) OR (
            reanchored_by_generation_id IS NOT NULL
            AND reanchored_at IS NOT NULL
            AND (gap_end_time IS NOT NULL OR gap_end_lsn IS NOT NULL)
        )
    ),
    CONSTRAINT coverage_gaps_lsn_order_check CHECK (
        gap_start_lsn IS NULL OR gap_end_lsn IS NULL OR gap_end_lsn > gap_start_lsn
    )
);

-- Durable, append-only intent for retiring one complete generation payload.
-- Destructive cleanup is deliberately a later transaction: admission rejects
-- `retiring` immediately, while a crash rolls back partial physical deletion
-- and leaves this row available for an idempotent retry.
CREATE TABLE IF NOT EXISTS flashback.generation_payload_retirements (
    retirement_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_id              BIGINT NOT NULL UNIQUE,
    tracking_id                BIGINT NOT NULL,
    state                      TEXT NOT NULL DEFAULT 'retiring'
                               CHECK (state IN ('retiring', 'removed')),
    reason                     TEXT NOT NULL CHECK (btrim(reason) <> ''),
    requested_at               TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    requested_by               NAME NOT NULL DEFAULT current_user,
    intent_txid                BIGINT NOT NULL DEFAULT txid_current(),
    snapshot_id                BIGINT NOT NULL,
    snapshot_table             TEXT NOT NULL CHECK (btrim(snapshot_table) <> ''),
    snapshot_rel_oid           OID,
    snapshot_row_count         BIGINT NOT NULL CHECK (snapshot_row_count >= 0),
    snapshot_schema_fingerprint TEXT NOT NULL
                               CHECK (snapshot_schema_fingerprint ~ '^[0-9a-f]{32}$'),
    expected_delta_rows        BIGINT NOT NULL CHECK (expected_delta_rows >= 0),
    expected_schema_rows       BIGINT NOT NULL CHECK (expected_schema_rows >= 0),
    first_delta_lsn            PG_LSN,
    last_delta_lsn             PG_LSN,
    delta_rows_removed         BIGINT,
    schema_rows_removed        BIGINT,
    removed_at                 TIMESTAMPTZ,
    removed_by                 NAME,
    details                    JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT generation_payload_retirements_generation_tracking_fk
        FOREIGN KEY (generation_id, tracking_id)
        REFERENCES flashback.coverage_generations(generation_id, tracking_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT generation_payload_retirements_snapshot_tracking_fk
        FOREIGN KEY (snapshot_id, tracking_id)
        REFERENCES flashback.snapshots(snapshot_id, tracking_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT generation_payload_retirements_removed_shape_check CHECK (
        (
            state = 'retiring'
            AND delta_rows_removed IS NULL
            AND schema_rows_removed IS NULL
            AND removed_at IS NULL
            AND removed_by IS NULL
        ) OR (
            state = 'removed'
            AND delta_rows_removed = expected_delta_rows
            AND schema_rows_removed = expected_schema_rows
            AND removed_at IS NOT NULL
            AND removed_by IS NOT NULL
        )
    ),
    CONSTRAINT generation_payload_retirements_snapshot_identity_check CHECK (
        state = 'removed' OR snapshot_rel_oid IS NOT NULL
    ),
    CONSTRAINT generation_payload_retirements_lsn_order_check CHECK (
        first_delta_lsn IS NULL OR last_delta_lsn IS NULL
        OR first_delta_lsn <= last_delta_lsn
    )
);

-- Upgrade retirement intents created before the physical snapshot relation
-- identity was frozen. Removed history may have no live OID; an in-progress
-- intent must resolve to the exact relation it plans to delete.
DO $$
BEGIN
    ALTER TABLE flashback.generation_payload_retirements
        ADD COLUMN IF NOT EXISTS snapshot_rel_oid OID;

    UPDATE flashback.generation_payload_retirements r
       SET snapshot_rel_oid = to_regclass(r.snapshot_table)::oid
     WHERE r.snapshot_rel_oid IS NULL
       AND r.state = 'retiring';

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.generation_payload_retirements'::regclass
          AND conname = 'generation_payload_retirements_snapshot_identity_check'
    ) THEN
        ALTER TABLE flashback.generation_payload_retirements
            ADD CONSTRAINT generation_payload_retirements_snapshot_identity_check
            CHECK (state = 'removed' OR snapshot_rel_oid IS NOT NULL) NOT VALID;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS generation_payload_retirements_tracking_state_idx
    ON flashback.generation_payload_retirements (tracking_id, state, requested_at);

CREATE OR REPLACE FUNCTION flashback_guard_generation_payload_retirement()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, flashback
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'pg_flashback: generation payload retirement audit % is immutable',
            OLD.retirement_id
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF NEW.state <> 'retiring' THEN
            RAISE EXCEPTION 'pg_flashback: generation payload retirement must start as retiring'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.state = 'removed' THEN
        RAISE EXCEPTION 'pg_flashback: removed payload retirement audit % is immutable',
            OLD.retirement_id
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF NEW.retirement_id IS DISTINCT FROM OLD.retirement_id
       OR NEW.generation_id IS DISTINCT FROM OLD.generation_id
       OR NEW.tracking_id IS DISTINCT FROM OLD.tracking_id
       OR NEW.reason IS DISTINCT FROM OLD.reason
       OR NEW.requested_at IS DISTINCT FROM OLD.requested_at
       OR NEW.requested_by IS DISTINCT FROM OLD.requested_by
       OR NEW.intent_txid IS DISTINCT FROM OLD.intent_txid
       OR NEW.snapshot_id IS DISTINCT FROM OLD.snapshot_id
       OR NEW.snapshot_table IS DISTINCT FROM OLD.snapshot_table
       OR NEW.snapshot_rel_oid IS DISTINCT FROM OLD.snapshot_rel_oid
       OR NEW.snapshot_row_count IS DISTINCT FROM OLD.snapshot_row_count
       OR NEW.snapshot_schema_fingerprint IS DISTINCT FROM OLD.snapshot_schema_fingerprint
       OR NEW.expected_delta_rows IS DISTINCT FROM OLD.expected_delta_rows
       OR NEW.expected_schema_rows IS DISTINCT FROM OLD.expected_schema_rows
       OR NEW.first_delta_lsn IS DISTINCT FROM OLD.first_delta_lsn
       OR NEW.last_delta_lsn IS DISTINCT FROM OLD.last_delta_lsn
       OR NEW.details IS DISTINCT FROM OLD.details
       OR NEW.state <> 'removed'
    THEN
        RAISE EXCEPTION 'pg_flashback: invalid payload retirement transition for audit %',
            OLD.retirement_id
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS generation_payload_retirements_guard
    ON flashback.generation_payload_retirements;
CREATE TRIGGER generation_payload_retirements_guard
BEFORE INSERT OR UPDATE OR DELETE ON flashback.generation_payload_retirements
FOR EACH ROW EXECUTE FUNCTION flashback_guard_generation_payload_retirement();

-- DDL payloads cannot be trusted when carried directly in a logical message:
-- pg_logical_emit_message() is executable by PUBLIC.  The ProcessUtility hook
-- stores the authoritative event in this protected LOGGED table inside the
-- user's transaction; the logical message carries no payload and only makes
-- the transaction's real COMMIT record visible to the decoder.  The worker
-- joins by stream/XID and deletes the row atomically after promotion.
CREATE TABLE IF NOT EXISTS flashback.pending_wal_events (
    pending_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id      BIGINT NOT NULL,
    generation_id    BIGINT NOT NULL,
    stream_id        BIGINT NOT NULL,
    source_xid       BIGINT NOT NULL,
    event_type       TEXT NOT NULL
                     CHECK (event_type IN ('TRUNCATE', 'DROP', 'ALTER')),
    table_name       TEXT NOT NULL CHECK (btrim(table_name) <> ''),
    rel_oid          OID NOT NULL,
    event_lsn        PG_LSN NOT NULL,
    schema_version   BIGINT NOT NULL CHECK (schema_version > 0),
    old_data         JSONB,
    new_data         JSONB,
    ddl_info         JSONB NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT pending_wal_events_generation_fk
        FOREIGN KEY (generation_id, tracking_id, stream_id)
        REFERENCES flashback.coverage_generations(
            generation_id, tracking_id, stream_id
        )
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS pending_wal_events_stream_xid_idx
    ON flashback.pending_wal_events (stream_id, source_xid, pending_event_id);

-- Upgrade an earlier scaffold whose audit rows incorrectly depended on the
-- deletable `tracked_tables` current binding.
DO $$
BEGIN
    -- Commit-time projections are diagnostic labels, not a monotonic clock.
    -- COMMIT LSN is the only canonical ordering coordinate in release scope.
    ALTER TABLE flashback.coverage_generations
        DROP CONSTRAINT IF EXISTS coverage_generations_time_order_check,
        DROP CONSTRAINT IF EXISTS coverage_generations_superseded_time_order_check,
        DROP CONSTRAINT IF EXISTS coverage_generations_watermark_applicability_time_check;
    ALTER TABLE flashback.coverage_gaps
        DROP CONSTRAINT IF EXISTS coverage_gaps_time_order_check;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback'
          AND table_name = 'coverage_generations'
          AND column_name = 'backup_anchor_id'
    ) THEN
        ALTER TABLE flashback.coverage_generations
            ADD COLUMN backup_anchor_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback'
          AND table_name = 'coverage_generations'
          AND column_name = 'canonical_coordinate_kind'
    ) THEN
        ALTER TABLE flashback.coverage_generations
            ADD COLUMN canonical_coordinate_kind TEXT GENERATED ALWAYS AS (
                CASE recovery_profile
                    WHEN 'local_delta' THEN 'commit_lsn'
                    WHEN 'backup' THEN 'physical_lsn'
                END
            ) STORED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback'
          AND table_name = 'coverage_generations'
          AND column_name = 'aborted_at'
    ) THEN
        ALTER TABLE flashback.coverage_generations
            ADD COLUMN aborted_at TIMESTAMPTZ;
    END IF;

    -- Keep failed, never-qualified boundaries as immutable audit tombstones.
    -- Older installs used an inline state check that did not know `aborted`.
    ALTER TABLE flashback.coverage_generations
        DROP CONSTRAINT IF EXISTS coverage_generations_state_check;
    ALTER TABLE flashback.coverage_generations
        ADD CONSTRAINT coverage_generations_state_check
        CHECK (state IN ('building', 'active', 'sealed', 'retired', 'aborted'));

    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.coverage_generations'::regclass
          AND conname = 'coverage_generations_tracking_profile_fk'
          AND confrelid <> 'flashback.tracking_lifecycles'::regclass
    ) THEN
        ALTER TABLE flashback.coverage_generations
            DROP CONSTRAINT coverage_generations_tracking_profile_fk;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.coverage_generations'::regclass
          AND conname = 'coverage_generations_tracking_profile_fk'
    ) THEN
        ALTER TABLE flashback.coverage_generations
            ADD CONSTRAINT coverage_generations_tracking_profile_fk
            FOREIGN KEY (tracking_id, recovery_profile)
            REFERENCES flashback.tracking_lifecycles(tracking_id, recovery_profile)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;

    ALTER TABLE flashback.coverage_generations
        DROP CONSTRAINT IF EXISTS coverage_generations_boundary_snapshot_tracking_fk;
    ALTER TABLE flashback.coverage_generations
        ADD CONSTRAINT coverage_generations_boundary_snapshot_tracking_fk
        FOREIGN KEY (boundary_snapshot_id, tracking_id, boundary_lsn)
        REFERENCES flashback.snapshots(snapshot_id, tracking_id, snapshot_lsn)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.coverage_generations'::regclass
          AND conname = 'coverage_generations_generation_tracking_stream_key'
    ) THEN
        ALTER TABLE flashback.coverage_generations
            ADD CONSTRAINT coverage_generations_generation_tracking_stream_key
            UNIQUE (generation_id, tracking_id, stream_id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.coverage_generations'::regclass
          AND conname = 'coverage_generations_backup_anchor_tracking_lsn_fk'
    ) THEN
        ALTER TABLE flashback.coverage_generations
            ADD CONSTRAINT coverage_generations_backup_anchor_tracking_lsn_fk
            FOREIGN KEY (backup_anchor_id, tracking_id, boundary_lsn)
            REFERENCES flashback.backup_anchors(
                backup_anchor_id, tracking_id, backup_stop_lsn
            )
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;

    -- An earlier scaffold allowed an active backup generation with only a
    -- naked LSN and allowed active local generations without a canonical WAL
    -- frontier. Replace those checks with profile-specific asset proof.
    ALTER TABLE flashback.coverage_generations
        DROP CONSTRAINT IF EXISTS coverage_generations_profile_shape_check,
        DROP CONSTRAINT IF EXISTS coverage_generations_state_shape_check,
        DROP CONSTRAINT IF EXISTS coverage_generations_applicability_shape_check;
    ALTER TABLE flashback.coverage_generations
        ADD CONSTRAINT coverage_generations_profile_shape_check CHECK (
            (
                recovery_profile = 'local_delta'
                AND stream_id IS NOT NULL
                AND boundary_snapshot_id IS NOT NULL
                AND backup_anchor_id IS NULL
            ) OR (
                recovery_profile = 'backup'
                AND stream_id IS NULL
                AND boundary_snapshot_id IS NULL
                AND (
                    state IN ('building', 'aborted')
                    OR (
                        backup_anchor_id IS NOT NULL
                        AND boundary_lsn IS NOT NULL
                        AND valid_through_lsn IS NOT NULL
                    )
                )
            )
        ),
        ADD CONSTRAINT coverage_generations_state_shape_check CHECK (
            (
                state = 'building'
                AND (
                    (boundary_time IS NOT NULL AND boundary_lsn IS NOT NULL)
                    OR boundary_xid IS NOT NULL
                    OR boundary_marker IS NOT NULL
                )
            ) OR (
                state = 'active'
                AND activated_at IS NOT NULL
                AND boundary_time IS NOT NULL
                AND boundary_lsn IS NOT NULL
                AND valid_through_lsn IS NOT NULL
            ) OR (
                state = 'sealed'
                AND sealed_at IS NOT NULL
                AND boundary_time IS NOT NULL
                AND boundary_lsn IS NOT NULL
                AND valid_through_lsn IS NOT NULL
            ) OR (
                state = 'retired'
                AND retired_at IS NOT NULL
                AND boundary_time IS NOT NULL
                AND boundary_lsn IS NOT NULL
                AND valid_through_lsn IS NOT NULL
            ) OR (
                state = 'aborted'
                AND aborted_at IS NOT NULL
            )
        ),
        ADD CONSTRAINT coverage_generations_applicability_shape_check CHECK (
            (
                state IN ('building', 'active', 'aborted')
                AND superseded_before_time IS NULL
                AND superseded_before_lsn IS NULL
            ) OR (
                state IN ('sealed', 'retired')
                AND superseded_before_lsn IS NOT NULL
            )
        );

    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.coverage_gaps'::regclass
          AND conname = 'coverage_gaps_tracking_fk'
          AND confrelid <> 'flashback.tracking_lifecycles'::regclass
    ) THEN
        ALTER TABLE flashback.coverage_gaps
            DROP CONSTRAINT coverage_gaps_tracking_fk;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.coverage_gaps'::regclass
          AND conname = 'coverage_gaps_tracking_fk'
    ) THEN
        ALTER TABLE flashback.coverage_gaps
            ADD CONSTRAINT coverage_gaps_tracking_fk
            FOREIGN KEY (tracking_id)
            REFERENCES flashback.tracking_lifecycles(tracking_id)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
END
$$;

-- Backup anchor evidence is append-only audit material.  It may be created
-- only after verification and is never edited into matching a generation.
CREATE OR REPLACE FUNCTION flashback_guard_backup_anchor_immutable()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, flashback
AS $$
BEGIN
    RAISE EXCEPTION 'pg_flashback: verified backup anchor % is immutable', OLD.backup_anchor_id
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

DROP TRIGGER IF EXISTS backup_anchors_immutable
    ON flashback.backup_anchors;
CREATE TRIGGER backup_anchors_immutable
BEFORE UPDATE OR DELETE ON flashback.backup_anchors
FOR EACH ROW EXECUTE FUNCTION flashback_guard_backup_anchor_immutable();

-- Once a generation is eligible, its ownership, boundary and applicability
-- identity are immutable. Only monotonic watermark advancement and the
-- successful lifecycle transitions building -> active -> sealed -> retired
-- remain legal. Failed, never-eligible building drafts become immutable
-- `aborted` audit tombstones after their physical payload is removed.
CREATE OR REPLACE FUNCTION flashback_guard_coverage_generation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, flashback
AS $$
DECLARE
    v_capture_mode text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'pg_flashback: generation % is immutable', OLD.generation_id
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF NEW.state NOT IN ('building', 'active') THEN
            RAISE EXCEPTION 'pg_flashback: a generation must be created as building or active'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
    ELSE
        IF OLD.state IN ('retired', 'aborted') THEN
            RAISE EXCEPTION 'pg_flashback: terminal generation % is immutable', OLD.generation_id
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;

        IF NOT (
            NEW.state = OLD.state
            OR (OLD.state = 'building' AND NEW.state = 'active')
            OR (OLD.state = 'building' AND NEW.state = 'aborted')
            OR (OLD.state = 'active' AND NEW.state = 'sealed')
            OR (OLD.state = 'sealed' AND NEW.state = 'retired')
        ) THEN
            RAISE EXCEPTION 'pg_flashback: invalid generation transition % -> %',
                OLD.state, NEW.state
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;

        IF NEW.generation_id IS DISTINCT FROM OLD.generation_id
           OR NEW.tracking_id IS DISTINCT FROM OLD.tracking_id
           OR NEW.generation_no IS DISTINCT FROM OLD.generation_no
           OR NEW.parent_generation_id IS DISTINCT FROM OLD.parent_generation_id
           OR NEW.stream_id IS DISTINCT FROM OLD.stream_id
           OR NEW.recovery_profile IS DISTINCT FROM OLD.recovery_profile
           OR NEW.boundary_kind IS DISTINCT FROM OLD.boundary_kind
           OR NEW.rel_oid_at_boundary IS DISTINCT FROM OLD.rel_oid_at_boundary
           OR NEW.boundary_snapshot_id IS DISTINCT FROM OLD.boundary_snapshot_id
           OR NEW.boundary_xid IS DISTINCT FROM OLD.boundary_xid
           OR NEW.boundary_marker IS DISTINCT FROM OLD.boundary_marker
           OR NEW.restored_target_time IS DISTINCT FROM OLD.restored_target_time
           OR NEW.restored_target_lsn IS DISTINCT FROM OLD.restored_target_lsn
           OR NEW.created_at IS DISTINCT FROM OLD.created_at
        THEN
            RAISE EXCEPTION 'pg_flashback: generation % ownership/lineage is immutable', OLD.generation_id
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;

        IF OLD.boundary_time IS NOT NULL
           AND NEW.boundary_time IS DISTINCT FROM OLD.boundary_time
        THEN
            RAISE EXCEPTION 'pg_flashback: generation % boundary time is immutable', OLD.generation_id
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF OLD.boundary_lsn IS NOT NULL
           AND NEW.boundary_lsn IS DISTINCT FROM OLD.boundary_lsn
        THEN
            RAISE EXCEPTION 'pg_flashback: generation % boundary LSN is immutable', OLD.generation_id
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF OLD.backup_anchor_id IS NOT NULL
           AND NEW.backup_anchor_id IS DISTINCT FROM OLD.backup_anchor_id
        THEN
            RAISE EXCEPTION 'pg_flashback: generation % backup anchor is immutable', OLD.generation_id
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF NEW.backup_anchor_id IS DISTINCT FROM OLD.backup_anchor_id
           AND OLD.state <> 'building'
        THEN
            RAISE EXCEPTION 'pg_flashback: backup anchor may be resolved only while building'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;

        IF OLD.valid_through_lsn IS NOT NULL
           AND (NEW.valid_through_lsn IS NULL
                OR NEW.valid_through_lsn < OLD.valid_through_lsn)
        THEN
            RAISE EXCEPTION 'pg_flashback: generation % watermark cannot move backward', OLD.generation_id
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;

        IF NEW.superseded_before_time IS DISTINCT FROM OLD.superseded_before_time
           OR NEW.superseded_before_lsn IS DISTINCT FROM OLD.superseded_before_lsn
        THEN
            IF NOT (OLD.state = 'active' AND NEW.state = 'sealed'
                    AND OLD.superseded_before_time IS NULL
                    AND OLD.superseded_before_lsn IS NULL)
            THEN
                RAISE EXCEPTION 'pg_flashback: generation applicability bound is immutable'
                    USING ERRCODE = 'integrity_constraint_violation';
            END IF;
        END IF;

        IF NEW.activated_at IS DISTINCT FROM OLD.activated_at
           AND NOT (OLD.state = 'building' AND NEW.state = 'active'
                    AND OLD.activated_at IS NULL AND NEW.activated_at IS NOT NULL)
        THEN
            RAISE EXCEPTION 'pg_flashback: invalid generation activation audit change'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF NEW.sealed_at IS DISTINCT FROM OLD.sealed_at
           AND NOT (OLD.state = 'active' AND NEW.state = 'sealed'
                    AND OLD.sealed_at IS NULL AND NEW.sealed_at IS NOT NULL)
        THEN
            RAISE EXCEPTION 'pg_flashback: invalid generation seal audit change'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF NEW.retired_at IS DISTINCT FROM OLD.retired_at
           AND NOT (OLD.state = 'sealed' AND NEW.state = 'retired'
                    AND OLD.retired_at IS NULL AND NEW.retired_at IS NOT NULL)
        THEN
            RAISE EXCEPTION 'pg_flashback: invalid generation retirement audit change'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF NEW.aborted_at IS DISTINCT FROM OLD.aborted_at
           AND NOT (OLD.state = 'building' AND NEW.state = 'aborted'
                    AND OLD.aborted_at IS NULL AND NEW.aborted_at IS NOT NULL)
        THEN
            RAISE EXCEPTION 'pg_flashback: invalid generation abort audit change'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF NEW.details IS DISTINCT FROM OLD.details AND OLD.state <> 'building' THEN
            RAISE EXCEPTION 'pg_flashback: qualified generation details are immutable'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
    END IF;

    -- The present scaffold fails trigger-local generations closed. If T-01
    -- later chooses a proven trigger total-order mechanism, it needs a new
    -- canonical coordinate type and an explicit schema migration.
    IF NEW.recovery_profile = 'local_delta'
       AND NEW.state IN ('active', 'sealed', 'retired')
    THEN
        SELECT capture_mode INTO v_capture_mode
        FROM flashback.capture_streams
        WHERE stream_id = NEW.stream_id;
        IF v_capture_mode IS DISTINCT FROM 'wal' THEN
            RAISE EXCEPTION 'pg_flashback: eligible local generation requires a WAL stream'
                USING ERRCODE = 'integrity_constraint_violation',
                      HINT = 'Trigger capture remains legacy/experimental until policy decision T-01 is implemented.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS coverage_generations_guard
    ON flashback.coverage_generations;
CREATE TRIGGER coverage_generations_guard
BEFORE INSERT OR UPDATE OR DELETE ON flashback.coverage_generations
FOR EACH ROW EXECUTE FUNCTION flashback_guard_coverage_generation();

CREATE UNIQUE INDEX IF NOT EXISTS capture_streams_one_active_idx
    ON flashback.capture_streams (database_oid)
    WHERE state = 'active';
CREATE UNIQUE INDEX IF NOT EXISTS coverage_generations_one_active_idx
    ON flashback.coverage_generations (tracking_id)
    WHERE state = 'active';
CREATE UNIQUE INDEX IF NOT EXISTS coverage_generations_one_building_idx
    ON flashback.coverage_generations (tracking_id)
    WHERE state = 'building';
CREATE INDEX IF NOT EXISTS coverage_generations_tracking_boundary_idx
    ON flashback.coverage_generations (tracking_id, boundary_time DESC);
CREATE UNIQUE INDEX IF NOT EXISTS coverage_generations_boundary_snapshot_once_idx
    ON flashback.coverage_generations (boundary_snapshot_id)
    WHERE boundary_snapshot_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS coverage_generations_boundary_marker_once_idx
    ON flashback.coverage_generations (boundary_marker)
    WHERE boundary_marker IS NOT NULL;
CREATE INDEX IF NOT EXISTS coverage_generations_parent_idx
    ON flashback.coverage_generations (parent_generation_id)
    WHERE parent_generation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS coverage_generations_stream_idx
    ON flashback.coverage_generations (stream_id)
    WHERE stream_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS coverage_gaps_tracking_open_idx
    ON flashback.coverage_gaps (tracking_id, detected_at DESC)
    WHERE reanchored_by_generation_id IS NULL;
CREATE INDEX IF NOT EXISTS coverage_gaps_tracking_idx
    ON flashback.coverage_gaps (tracking_id);
CREATE INDEX IF NOT EXISTS coverage_gaps_source_generation_idx
    ON flashback.coverage_gaps (source_generation_id);
CREATE INDEX IF NOT EXISTS coverage_gaps_reanchor_generation_idx
    ON flashback.coverage_gaps (reanchored_by_generation_id)
    WHERE reanchored_by_generation_id IS NOT NULL;

-- DDL hooks can record statement-time evidence immediately, but a long
-- transaction is admitted to a generation only after its commit is observed.
-- These nullable bindings keep legacy rows honest while allowing the
-- qualification worker to attach commit coordinates later.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.schema_versions'::regclass
          AND conname = 'schema_versions_tracking_fk'
          AND confrelid <> 'flashback.tracking_lifecycles'::regclass
    ) THEN
        ALTER TABLE flashback.schema_versions
            DROP CONSTRAINT schema_versions_tracking_fk;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.schema_versions'::regclass
          AND conname = 'schema_versions_tracking_fk'
    ) THEN
        ALTER TABLE flashback.schema_versions
            ADD CONSTRAINT schema_versions_tracking_fk
            FOREIGN KEY (tracking_id)
            REFERENCES flashback.tracking_lifecycles(tracking_id)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.schema_versions'::regclass
          AND conname = 'schema_versions_generation_tracking_fk'
    ) THEN
        ALTER TABLE flashback.schema_versions
            ADD CONSTRAINT schema_versions_generation_tracking_fk
            FOREIGN KEY (generation_id, tracking_id)
            REFERENCES flashback.coverage_generations(generation_id, tracking_id)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.schema_versions'::regclass
          AND conname = 'schema_versions_stream_fk'
    ) THEN
        ALTER TABLE flashback.schema_versions
            ADD CONSTRAINT schema_versions_stream_fk
            FOREIGN KEY (stream_id)
            REFERENCES flashback.capture_streams(stream_id)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.schema_versions'::regclass
          AND conname = 'schema_versions_generation_tracking_stream_fk'
    ) THEN
        ALTER TABLE flashback.schema_versions
            ADD CONSTRAINT schema_versions_generation_tracking_stream_fk
            FOREIGN KEY (generation_id, tracking_id, stream_id)
            REFERENCES flashback.coverage_generations(
                generation_id, tracking_id, stream_id
            )
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.schema_versions'::regclass
          AND conname = 'schema_versions_binding_shape_check'
    ) THEN
        ALTER TABLE flashback.schema_versions
            ADD CONSTRAINT schema_versions_binding_shape_check
            CHECK (generation_id IS NULL OR tracking_id IS NOT NULL);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'schema_versions'
          AND column_name = 'helper_schema_sha256'
    ) THEN
        ALTER TABLE flashback.schema_versions ADD COLUMN helper_schema_sha256 TEXT;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'flashback_import') THEN
        EXECUTE 'CREATE SCHEMA flashback_import';
    END IF;
    IF to_regclass('flashback.backup_restore_request_seq') IS NULL THEN
        EXECUTE 'CREATE SEQUENCE flashback.backup_restore_request_seq';
    END IF;
    IF to_regclass('flashback.backup_restore_requests') IS NULL THEN
        EXECUTE 'CREATE TABLE flashback.backup_restore_requests (
            request_id              TEXT PRIMARY KEY,
            rel_oid                 OID NOT NULL,
            tracking_id             BIGINT,
            generation_id           BIGINT,
            schema_name             TEXT NOT NULL,
            table_name              TEXT NOT NULL,
            target_lsn              PG_LSN NOT NULL,
            expected_schema_version BIGINT NOT NULL,
            expected_schema_sha256  TEXT,
            helper_profile          TEXT NOT NULL,
            request_json            JSONB NOT NULL,
            status                  TEXT NOT NULL DEFAULT ''pending'',
            result_json             JSONB,
            artifact_schema         TEXT,
            artifact_table          TEXT,
            artifact_sha256         TEXT,
            requested_by            NAME NOT NULL DEFAULT current_user,
            created_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
            updated_at              TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
            completed_at            TIMESTAMPTZ,
            error_message           TEXT,
            CONSTRAINT backup_restore_status_check
                CHECK (status IN (''pending'', ''running'', ''artifact_ready'', ''completed'', ''failed'', ''cancelled'')),
            CONSTRAINT backup_restore_requests_tracking_fk
                FOREIGN KEY (tracking_id)
                REFERENCES flashback.tracking_lifecycles(tracking_id)
                ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT backup_restore_requests_generation_tracking_fk
                FOREIGN KEY (generation_id, tracking_id)
                REFERENCES flashback.coverage_generations(generation_id, tracking_id)
                ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT backup_restore_requests_binding_shape_check
                CHECK (generation_id IS NULL OR tracking_id IS NOT NULL)
        )';
    END IF;
END
$$;

-- Backup requests remain legacy/unqualified until runtime admission pins a
-- generation. Nullable bindings avoid inventing coverage for existing rows.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.backup_restore_requests'::regclass
          AND conname = 'backup_restore_requests_tracking_fk'
          AND confrelid <> 'flashback.tracking_lifecycles'::regclass
    ) THEN
        ALTER TABLE flashback.backup_restore_requests
            DROP CONSTRAINT backup_restore_requests_tracking_fk;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'backup_restore_requests'
          AND column_name = 'tracking_id'
    ) THEN
        ALTER TABLE flashback.backup_restore_requests ADD COLUMN tracking_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'backup_restore_requests'
          AND column_name = 'generation_id'
    ) THEN
        ALTER TABLE flashback.backup_restore_requests ADD COLUMN generation_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.backup_restore_requests'::regclass
          AND conname = 'backup_restore_requests_tracking_fk'
    ) THEN
        ALTER TABLE flashback.backup_restore_requests
            ADD CONSTRAINT backup_restore_requests_tracking_fk
            FOREIGN KEY (tracking_id)
            REFERENCES flashback.tracking_lifecycles(tracking_id)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.backup_restore_requests'::regclass
          AND conname = 'backup_restore_requests_generation_tracking_fk'
    ) THEN
        ALTER TABLE flashback.backup_restore_requests
            ADD CONSTRAINT backup_restore_requests_generation_tracking_fk
            FOREIGN KEY (generation_id, tracking_id)
            REFERENCES flashback.coverage_generations(generation_id, tracking_id)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.backup_restore_requests'::regclass
          AND conname = 'backup_restore_requests_binding_shape_check'
    ) THEN
        ALTER TABLE flashback.backup_restore_requests
            ADD CONSTRAINT backup_restore_requests_binding_shape_check
            CHECK (generation_id IS NULL OR tracking_id IS NOT NULL);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS backup_restore_requests_status_created_idx
    ON flashback.backup_restore_requests (status, created_at);
CREATE INDEX IF NOT EXISTS backup_restore_requests_generation_idx
    ON flashback.backup_restore_requests (generation_id)
    WHERE generation_id IS NOT NULL;

DO $$
BEGIN
    IF to_regclass('flashback.schema_versions_rel_oid_applied_at_idx') IS NULL THEN
        EXECUTE 'CREATE INDEX schema_versions_rel_oid_applied_at_idx ON flashback.schema_versions (rel_oid, applied_at DESC)';
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('flashback.snapshots_rel_oid_captured_at_idx') IS NULL THEN
        EXECUTE 'CREATE INDEX snapshots_rel_oid_captured_at_idx ON flashback.snapshots (rel_oid, captured_at DESC)';
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('flashback.delta_log_rel_oid_event_time_idx') IS NULL THEN
        EXECUTE 'CREATE INDEX delta_log_rel_oid_event_time_idx ON flashback.delta_log (rel_oid, event_time) WHERE committed_at IS NOT NULL';
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('flashback.delta_log_rel_oid_committed_at_idx') IS NULL THEN
        EXECUTE 'CREATE INDEX delta_log_rel_oid_committed_at_idx ON flashback.delta_log (rel_oid, committed_at DESC)';
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS delta_log_generation_commit_idx
    ON flashback.delta_log (generation_id, committed_at, event_id)
    WHERE generation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS snapshots_tracking_captured_idx
    ON flashback.snapshots (tracking_id, captured_at DESC)
    WHERE tracking_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS schema_versions_tracking_applied_idx
    ON flashback.schema_versions (tracking_id, applied_at DESC)
    WHERE tracking_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS schema_versions_source_xid_pending_idx
    ON flashback.schema_versions (source_xid)
    WHERE source_xid IS NOT NULL AND committed_at IS NULL;
CREATE INDEX IF NOT EXISTS schema_versions_generation_commit_idx
    ON flashback.schema_versions (generation_id, committed_at, version_id)
    WHERE generation_id IS NOT NULL;

DO $$
BEGIN
    IF to_regclass('flashback.staging_events') IS NULL THEN
        EXECUTE 'CREATE TABLE flashback.staging_events (
            staging_id  BIGSERIAL PRIMARY KEY,
            event_time  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
            rel_oid     OID NOT NULL,
            tracking_id BIGINT,
            generation_id BIGINT,
            stream_id   BIGINT,
            source_xid  BIGINT NOT NULL
                        DEFAULT ((txid_current() % 4294967296)::bigint),
            event_type  TEXT NOT NULL,
            table_name  TEXT NOT NULL,
            old_data    JSONB,
            new_data    JSONB
        )';
    END IF;
END
$$;

-- Upgrade old installations that predate the LOGGED staging fix. This takes
-- an ACCESS EXCLUSIVE lock and may rewrite the relation, but leaving it
-- UNLOGGED would silently lose committed capture on crash.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'flashback'
          AND c.relname = 'staging_events'
          AND c.relpersistence = 'u'
    ) THEN
        ALTER TABLE flashback.staging_events SET LOGGED;
        RAISE NOTICE 'pg_flashback: converted legacy staging_events to LOGGED';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'staging_events'
          AND column_name = 'tracking_id'
    ) THEN
        ALTER TABLE flashback.staging_events ADD COLUMN tracking_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'staging_events'
          AND column_name = 'generation_id'
    ) THEN
        ALTER TABLE flashback.staging_events ADD COLUMN generation_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'staging_events'
          AND column_name = 'stream_id'
    ) THEN
        ALTER TABLE flashback.staging_events ADD COLUMN stream_id BIGINT;
    END IF;
END
$$;

-- A legacy payload has no coverage binding at all. Once wiring starts, the
-- three IDs travel as one tuple captured in the user's transaction; accepting
-- a partial or cross-generation tuple would permit worker-flush misrouting.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.delta_log'::regclass
          AND conname = 'delta_log_tracking_fk'
    ) THEN
        ALTER TABLE flashback.delta_log
            ADD CONSTRAINT delta_log_tracking_fk
            FOREIGN KEY (tracking_id)
            REFERENCES flashback.tracking_lifecycles(tracking_id)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.delta_log'::regclass
          AND conname = 'delta_log_generation_tracking_stream_fk'
    ) THEN
        ALTER TABLE flashback.delta_log
            ADD CONSTRAINT delta_log_generation_tracking_stream_fk
            FOREIGN KEY (generation_id, tracking_id, stream_id)
            REFERENCES flashback.coverage_generations(
                generation_id, tracking_id, stream_id
            )
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.delta_log'::regclass
          AND conname = 'delta_log_binding_shape_check'
    ) THEN
        ALTER TABLE flashback.delta_log
            ADD CONSTRAINT delta_log_binding_shape_check CHECK (
                (
                    tracking_id IS NULL
                    AND generation_id IS NULL
                    AND stream_id IS NULL
                ) OR (
                    tracking_id IS NOT NULL
                    AND generation_id IS NOT NULL
                    AND stream_id IS NOT NULL
                    AND commit_lsn IS NOT NULL
                )
            );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.staging_events'::regclass
          AND conname = 'staging_events_tracking_fk'
    ) THEN
        ALTER TABLE flashback.staging_events
            ADD CONSTRAINT staging_events_tracking_fk
            FOREIGN KEY (tracking_id)
            REFERENCES flashback.tracking_lifecycles(tracking_id)
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.staging_events'::regclass
          AND conname = 'staging_events_generation_tracking_stream_fk'
    ) THEN
        ALTER TABLE flashback.staging_events
            ADD CONSTRAINT staging_events_generation_tracking_stream_fk
            FOREIGN KEY (generation_id, tracking_id, stream_id)
            REFERENCES flashback.coverage_generations(
                generation_id, tracking_id, stream_id
            )
            ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.staging_events'::regclass
          AND conname = 'staging_events_binding_shape_check'
    ) THEN
        ALTER TABLE flashback.staging_events
            ADD CONSTRAINT staging_events_binding_shape_check CHECK (
                (
                    tracking_id IS NULL
                    AND generation_id IS NULL
                    AND stream_id IS NULL
                ) OR (
                    tracking_id IS NOT NULL
                    AND generation_id IS NOT NULL
                    AND stream_id IS NOT NULL
                )
            );
    END IF;
END
$$;

-- lz4 compression for staging_events JSONB columns
DO $$
BEGIN
    IF to_regclass('flashback.staging_events') IS NOT NULL THEN
        BEGIN
            ALTER TABLE flashback.staging_events ALTER COLUMN old_data SET COMPRESSION lz4;
            ALTER TABLE flashback.staging_events ALTER COLUMN new_data SET COMPRESSION lz4;
        EXCEPTION WHEN feature_not_supported THEN
            NULL; -- silently skip if lz4 not available
        END;
    END IF;
END
$$;

DO $$
BEGIN
    IF to_regclass('flashback.restore_log') IS NULL THEN
        EXECUTE 'CREATE TABLE flashback.restore_log (
            restore_id     BIGSERIAL PRIMARY KEY,
            table_name     TEXT NOT NULL,
            target_time    TIMESTAMPTZ,
            target_lsn     PG_LSN,
            restored_by    TEXT NOT NULL DEFAULT current_user,
            restored_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            rows_affected  BIGINT NOT NULL DEFAULT 0,
            success        BOOLEAN NOT NULL DEFAULT true,
            error_message  TEXT
        )';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'flashback' AND table_name = 'restore_log'
          AND column_name = 'target_lsn'
    ) THEN
        ALTER TABLE flashback.restore_log ADD COLUMN target_lsn PG_LSN;
    END IF;
    ALTER TABLE flashback.restore_log ALTER COLUMN target_time DROP NOT NULL;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'flashback.restore_log'::regclass
          AND conname = 'restore_log_target_coordinate_check'
    ) THEN
        ALTER TABLE flashback.restore_log
            ADD CONSTRAINT restore_log_target_coordinate_check
            CHECK (target_time IS NOT NULL OR target_lsn IS NOT NULL);
    END IF;
END
$$;

-- Enhanced monitoring view with per-table storage breakdown
CREATE OR REPLACE VIEW flashback.pg_stat_flashback AS
SELECT
    (SELECT count(*) FROM flashback.tracked_tables WHERE is_active) AS tracked_tables,
    (SELECT count(*) FROM flashback.tracked_tables WHERE NOT is_active) AS untracked_tables,
    (SELECT count(*) FROM flashback.staging_events) AS pending_events,
    (SELECT count(*) FROM flashback.delta_log) AS total_deltas,
    (SELECT pg_size_pretty(pg_total_relation_size('flashback.delta_log'))) AS delta_storage,
    (SELECT pg_size_pretty(pg_total_relation_size('flashback.staging_events'))) AS staging_storage,
    (SELECT count(*) FROM flashback.snapshots) AS total_snapshots,
    (SELECT count(*) FROM flashback.restore_log) AS total_restores,
    (SELECT count(*) FROM flashback.restore_log WHERE success) AS successful_restores,
    (SELECT count(*) FROM flashback.restore_log WHERE NOT success) AS failed_restores,
    (SELECT max(restored_at) FROM flashback.restore_log) AS last_restore_at,
    COALESCE(current_setting('pg_flashback.enabled', true), 'on') AS capture_enabled,
    COALESCE(current_setting('pg_flashback.max_row_size', true), '64kB') AS max_row_size,
    COALESCE(current_setting('pg_flashback.worker_interval_ms', true), '75') AS worker_interval_ms;

-- Per-table storage breakdown for capacity planning
CREATE OR REPLACE VIEW flashback.pg_stat_flashback_tables AS
SELECT
    format('%I.%I', tt.schema_name, tt.table_name) AS table_name,
    tt.tracked_since,
    tt.checkpoint_interval,
    tt.retention_interval,
    tt.is_active,
    (SELECT count(*) FROM flashback.delta_log d
     WHERE d.tracking_id = tt.tracking_id
        OR (d.tracking_id IS NULL AND d.rel_oid = tt.rel_oid)) AS delta_count,
    (SELECT pg_size_pretty(
        COALESCE(sum(pg_column_size(d.old_data) + pg_column_size(d.new_data)), 0)::bigint
    ) FROM flashback.delta_log d
      WHERE d.tracking_id = tt.tracking_id
         OR (d.tracking_id IS NULL AND d.rel_oid = tt.rel_oid)) AS delta_data_size,
    (SELECT count(*) FROM flashback.snapshots s
     WHERE s.tracking_id = tt.tracking_id
        OR (s.tracking_id IS NULL AND s.rel_oid = tt.rel_oid)) AS snapshot_count,
    (SELECT max(s.captured_at) FROM flashback.snapshots s
     WHERE s.tracking_id = tt.tracking_id
        OR (s.tracking_id IS NULL AND s.rel_oid = tt.rel_oid)) AS last_checkpoint_at,
    (SELECT count(*) FROM flashback.restore_log r
     WHERE r.table_name = format('%I.%I', tt.schema_name, tt.table_name)) AS restore_count
FROM flashback.tracked_tables tt;

-- No recovery or tracking state is extension configuration data.  A logical
-- dump cannot preserve relation OIDs, logical-slot incarnations, partitioned
-- delta payload, or the sequence state needed to qualify this state as one
-- coherent restore chain.  Exporting only a subset is fail-open: it can make a
-- restored database appear tracked while its history is missing.  pg_dump
-- therefore recreates an empty pg_flashback installation; every table must be
-- explicitly tracked again to establish a fresh exact boundary.
