#!/usr/bin/env bash
# Byte-based local_delta support-envelope benchmark.
# Measures protect/DROP/recover cost by table size + shape, not whole-DB size.
#
# Requires a live cluster with pg_flashback installed (PG* / libpq).
# Results go under target/ (never commit). Trap cleans relations/slots leftovers
# created by this script only.
#
# Usage:
#   PGHOST=... PGDATABASE=... ./scripts/run_byte_support_envelope_bench.sh
#   PG_FLASHBACK_BENCH_SIZES="10MiB 100MiB" ./scripts/run_byte_support_envelope_bench.sh

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESULT_DIR="${PG_FLASHBACK_BENCH_RESULT_DIR:-$ROOT/target/bench}"
RUN_ID="$(date -u +%Y%m%dT%H%M%SZ)-$$"
OUT_JSON="$RESULT_DIR/byte-support-envelope-$RUN_ID.json"
SIZES="${PG_FLASHBACK_BENCH_SIZES:-10MiB 100MiB 500MiB 1GiB}"
SHAPES="${PG_FLASHBACK_BENCH_SHAPES:-narrow indexed toast churn}"
MAX_TEMP_BYTES="${PG_FLASHBACK_BENCH_MAX_TEMP_BYTES:-$((8 * 1024 * 1024 * 1024))}"
mkdir -p "$RESULT_DIR"

PSQL_BIN="${PSQL_BIN:-psql}"
psqlq() { "$PSQL_BIN" -X -v ON_ERROR_STOP=1 -qAt "$@"; }

CREATED_TABLES=()
cleanup() {
    local t
    for t in "${CREATED_TABLES[@]+"${CREATED_TABLES[@]}"}"; do
        psqlq -c "SELECT flashback_unprotect('$t');" >/dev/null 2>&1 || true
        psqlq -c "DROP TABLE IF EXISTS $t CASCADE;" >/dev/null 2>&1 || true
    done
}
trap cleanup EXIT

size_to_bytes() {
    case "$1" in
        10MiB) echo $((10 * 1024 * 1024)) ;;
        100MiB) echo $((100 * 1024 * 1024)) ;;
        500MiB) echo $((500 * 1024 * 1024)) ;;
        1GiB) echo $((1024 * 1024 * 1024)) ;;
        *) echo "$1" | awk '/^[0-9]+$/ {print; exit} {exit 1}' || { echo "bad size $1" >&2; exit 2; } ;;
    esac
}

host_meta="$(psqlq <<'SQL'
SELECT jsonb_build_object(
  'postgresql_version', version(),
  'database', current_database(),
  'server_encoding', current_setting('server_encoding'),
  'shared_buffers', current_setting('shared_buffers'),
  'max_worker_processes', current_setting('max_worker_processes'),
  'max_slot_wal_keep_size', current_setting('max_slot_wal_keep_size'),
  'local_max_snapshot_bytes', current_setting('pg_flashback.local_max_snapshot_bytes', true),
  'local_max_restore_peak_bytes', current_setting('pg_flashback.local_max_restore_peak_bytes', true),
  'local_min_filesystem_bytes', current_setting('pg_flashback.local_min_filesystem_bytes', true),
  'filesystem_available_bytes', flashback_tablespace_filesystem_available_bytes(0)
);
SQL
)"

RESULTS='[]'
for size_label in $SIZES; do
  bytes="$(size_to_bytes "$size_label")"
  # Rough temp budget: base + restore peak (~3x) + indexes headroom.
  need=$((bytes * 4))
  if (( need > MAX_TEMP_BYTES )); then
    echo "SKIP $size_label: projected temp $need exceeds MAX_TEMP_BYTES=$MAX_TEMP_BYTES" >&2
    continue
  fi
  avail="$(printf '%s' "$host_meta" | jq -r '.filesystem_available_bytes // 0')"
  if (( avail > 0 && need > avail / 2 )); then
    echo "SKIP $size_label: need~$need but filesystem_available=$avail" >&2
    continue
  fi

  for shape in $SHAPES; do
    size_slug=$(printf '%s' "$size_label" | tr '[:upper:]' '[:lower:]')
    rel="public.bench_${shape}_${size_slug}"
    CREATED_TABLES+=("$rel")
    echo "== $rel =="

    case "$shape" in
      narrow)
        ddl="CREATE TABLE $rel (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v int NOT NULL);"
        # ~16 bytes/row rough → rows
        rows=$(( bytes / 16 ))
        load="INSERT INTO $rel(v) SELECT g FROM generate_series(1,$rows) g;"
        churn=""
        ;;
      indexed)
        ddl="CREATE TABLE $rel (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              a int NOT NULL, b int NOT NULL, c text NOT NULL,
              UNIQUE (a), CHECK (b >= 0));
             CREATE INDEX ON $rel (b); CREATE INDEX ON $rel (lower(c));"
        rows=$(( bytes / 64 ))
        load="INSERT INTO $rel(a,b,c) SELECT g, g%1000, 'x'||g FROM generate_series(1,$rows) g;"
        churn=""
        ;;
      toast)
        ddl="CREATE TABLE $rel (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, blob text NOT NULL);"
        # ~2KiB payload
        rows=$(( bytes / 2048 ))
        load="INSERT INTO $rel(blob) SELECT repeat('z', 2048) FROM generate_series(1,$rows) g;"
        churn=""
        ;;
      churn)
        ddl="CREATE TABLE $rel (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v int NOT NULL, note text);"
        rows=$(( bytes / 32 ))
        load="INSERT INTO $rel(v,note) SELECT g, 'n' FROM generate_series(1,$rows) g;"
        churn="UPDATE $rel SET v = v + 1 WHERE id % 3 = 0;
               DELETE FROM $rel WHERE id % 11 = 0;
               INSERT INTO $rel(v,note) SELECT g, 'c' FROM generate_series($((rows+1)), $((rows + rows/10))) g;"
        ;;
      *) echo "unknown shape $shape" >&2; exit 2 ;;
    esac

    psqlq -c "DROP TABLE IF EXISTS $rel CASCADE;"
    t0=$(date +%s%N)
    psqlq -c "$ddl"
    # protect
    psqlq -c "SELECT flashback_track('$rel');"
    # wait healthy
    for _ in $(seq 1 240); do
      h=$(psqlq -c "SELECT flashback_lifecycle_health('$rel');")
      [[ "$h" == "healthy" ]] && break
      sleep 0.25
    done
    t_protect=$(( ($(date +%s%N) - t0) / 1000000 ))

    disk_before=$(psqlq -c "SELECT COALESCE((flashback_disk_retention_status())->>'total_bytes','0')::bigint;")
    psqlq -c "$load"
    if [[ -n "$churn" ]]; then
      psqlq -c "$churn"
    fi
    for _ in $(seq 1 240); do
      h=$(psqlq -c "SELECT flashback_lifecycle_health('$rel');")
      [[ "$h" == "healthy" ]] && break
      sleep 0.25
    done
    disk_after_dml=$(psqlq -c "SELECT COALESCE((flashback_disk_retention_status())->>'total_bytes','0')::bigint;")
    fp=$(psqlq -c "SELECT md5(count(*)::text || ':' || coalesce(sum(hashtext(t::text)),0)::text) FROM $rel t;")
    rows_live=$(psqlq -c "SELECT count(*) FROM $rel;")

    t1=$(date +%s%N)
    psqlq -c "DROP TABLE $rel;"
    # discovery
    for _ in $(seq 1 240); do
      st=$(psqlq -c "SELECT status FROM flashback_disaster_points('$rel', interval '1 day') WHERE event_type='DROP' ORDER BY disaster_commit_lsn DESC LIMIT 1;")
      [[ "$st" == "restorable" ]] && break
      sleep 0.25
    done
    t_discover=$(( ($(date +%s%N) - t1) / 1000000 ))

    t2=$(date +%s%N)
    plan=$(psqlq -c "SELECT flashback_recover_plan('$rel', interval '1 day');")
    t_dry=$(( ($(date +%s%N) - t2) / 1000000 ))
    token=$(printf '%s' "$plan" | jq -r '.plan_token')
    [[ -n "$token" && "$token" != "null" ]] || { echo "FAIL plan $rel" >&2; exit 1; }

    t3=$(date +%s%N)
    op=$(psqlq -c "SELECT flashback_recover_begin('$rel', '$token', interval '1 day')->>'operation_id';")
    psqlq -c "SELECT flashback_recover_execute('$rel', '$token', interval '1 day', NULL, NULL, NULL, $op);" >/dev/null
    for _ in $(seq 1 300); do
      st=$(psqlq -c "SELECT COALESCE(flashback_operation_state($op),'missing');")
      [[ "$st" == "verified" || "$st" == "failed" ]] && break
      sleep 0.5
    done
    t_recover=$(( ($(date +%s%N) - t3) / 1000000 ))
    fp2=$(psqlq -c "SELECT md5(count(*)::text || ':' || coalesce(sum(hashtext(t::text)),0)::text) FROM $rel t;")
    ok=$([[ "$fp" == "$fp2" && "$st" == "verified" ]] && echo true || echo false)
    disk_peak=$(psqlq -c "SELECT COALESCE((flashback_disk_retention_status())->>'total_bytes','0')::bigint;")

    t4=$(date +%s%N)
    psqlq -c "SELECT flashback_maintain_plan('$rel');" >/dev/null || true
    # maintain is optional; measure plan only to avoid long reanchor on large tables by default
    t_maintain_plan=$(( ($(date +%s%N) - t4) / 1000000 ))

    tid=$(psqlq -c "SELECT (SELECT tracking_id::text FROM jsonb_array_elements(flashback_list_lifecycles()) e WHERE e->>'table_name' = '$rel' LIMIT 1);")
    t5=$(date +%s%N)
    psqlq -c "SELECT flashback_unprotect('$rel');" >/dev/null
    for _ in $(seq 1 120); do
      st=$(psqlq -c "SELECT COALESCE((SELECT e->>'protection_state' FROM jsonb_array_elements(flashback_list_lifecycles()) e WHERE (e->>'tracking_id') = '$tid' LIMIT 1), 'gone');")
      [[ "$st" == "unprotected" || "$st" == "gone" || "$st" == "inactive" ]] && break
      # also try finalize
      psqlq -c "SELECT flashback_finalize_unprotect_operations();" >/dev/null 2>&1 || true
      sleep 0.5
    done
    if [[ -n "$tid" && "$tid" != "null" ]]; then
      psqlq -c "SELECT flashback_cleanup($tid::bigint, false);" >/dev/null 2>&1 || true
    fi
    psqlq -c "DROP TABLE IF EXISTS $rel CASCADE;"
    t_cleanup=$(( ($(date +%s%N) - t5) / 1000000 ))

    RESULTS=$(jq -n --argjson acc "$RESULTS" \
      --arg size "$size_label" --argjson bytes "$bytes" --arg shape "$shape" \
      --arg rel "$rel" --argjson protect_ms "$t_protect" --argjson discover_ms "$t_discover" \
      --argjson dry_run_ms "$t_dry" --argjson recover_ms "$t_recover" \
      --argjson maintain_plan_ms "$t_maintain_plan" --argjson cleanup_ms "$t_cleanup" \
      --argjson rows "$rows_live" --argjson disk_before "$disk_before" \
      --argjson disk_after_dml "$disk_after_dml" --argjson disk_peak "$disk_peak" \
      --argjson ok "$ok" --arg op_state "$st" \
      '$acc + [{
        size_label:$size, target_bytes:$bytes, shape:$shape, table:$rel,
        protect_ms:$protect_ms, drop_discovery_ms:$discover_ms, dry_run_ms:$dry_run_ms,
        recover_ms:$recover_ms, maintain_plan_ms:$maintain_plan_ms, cleanup_ms:$cleanup_ms,
        rows:$rows, disk_before_bytes:$disk_before, disk_after_dml_bytes:$disk_after_dml,
        disk_peak_bytes:$disk_peak, fingerprint_ok:$ok, operation_state:$op_state
      }]')
  done
done

jq -n --argjson host "$host_meta" --argjson results "$RESULTS" --arg run "$RUN_ID" \
  '{schema_version:1, run_id:$run, host:$host, results:$results,
    note:"Support envelope is host/config specific; do not claim universal 1GiB support."}' \
  > "$OUT_JSON"
echo "Wrote $OUT_JSON"
jq -r '.results[] | "\(.size_label)\t\(.shape)\tprotect=\(.protect_ms)ms recover=\(.recover_ms)ms ok=\(.fingerprint_ok)"' "$OUT_JSON"
