#!/usr/bin/env bash
# Exact event-bound dependency manifest fail-closed regressions.
# Requires a live PG* cluster with pg_flashback installed.
set -Eeuo pipefail

PSQL_BIN="${PSQL_BIN:-psql}"
psqlq() { "$PSQL_BIN" -X -v ON_ERROR_STOP=1 -qAt "$@"; }

if [[ "${REQUIRE_LIVE:-0}" != "1" && -z "${PGDATABASE:-}" && -z "${PGHOST:-}" ]]; then
    echo "SKIP: set PG* / REQUIRE_LIVE=1 for live exact-manifest matrix" >&2
    exit 0
fi

cleanup() {
    psqlq -c "SELECT flashback_unprotect('public.em_exact');" >/dev/null 2>&1 || true
    psqlq -c "DROP TABLE IF EXISTS public.em_exact CASCADE;" >/dev/null 2>&1 || true
    psqlq -c "DROP VIEW IF EXISTS public.em_exact_v CASCADE;" >/dev/null 2>&1 || true
}
trap cleanup EXIT

psqlq <<'SQL'
DROP VIEW IF EXISTS public.em_exact_v CASCADE;
DROP TABLE IF EXISTS public.em_exact CASCADE;
CREATE TABLE public.em_exact(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    n text NOT NULL
);
INSERT INTO public.em_exact(n) VALUES ('a');
SELECT flashback_track('public.em_exact');
SQL

for _ in $(seq 1 120); do
    h=$(psqlq -c "SELECT flashback_lifecycle_health('public.em_exact');")
    [[ "$h" == "healthy" ]] && break
    sleep 0.25
done
[[ "$h" == "healthy" ]] || { echo "FAIL: not healthy"; exit 1; }

tid=$(psqlq -c "SELECT (flashback_list_lifecycles()->0->>'tracking_id');")

# Identity-less call must fail closed.
set +e
out=$(psqlq -c "SELECT flashback_require_supported_drop_manifest($tid);" 2>&1)
rc=$?
set -e
[[ $rc -ne 0 ]] || { echo "FAIL: identity-less call succeeded"; exit 1; }
printf '%s' "$out" | grep -qi 'exact DROP identity required' || {
    echo "FAIL: unexpected identity-less error: $out"; exit 1;
}
echo "PASS: identity-less refuse"

psqlq -c "DROP TABLE public.em_exact;"
for _ in $(seq 1 120); do
    st=$(psqlq -c "SELECT status FROM flashback_disaster_points('public.em_exact', interval '1 day') WHERE event_type='DROP' ORDER BY disaster_commit_lsn DESC LIMIT 1;")
    [[ "$st" == "restorable" || "$st" == "non_restorable" ]] && break
    sleep 0.25
done

plan=$(psqlq -c "SELECT flashback_recover_plan('public.em_exact', interval '1 day');")
code=$(printf '%s' "$plan" | jq -r '.code')
eid=$(printf '%s' "$plan" | jq -r '.disaster_event_id // empty')
[[ -n "$eid" && "$eid" != "null" ]] || { echo "FAIL: no disaster_event_id in plan code=$code"; echo "$plan"; exit 1; }

# Wrong event id must fail closed (not fall back to latest).
set +e
out=$(psqlq -c "SELECT flashback_require_supported_drop_manifest($tid, ($eid + 999999)::bigint);" 2>&1)
rc=$?
set -e
[[ $rc -ne 0 ]] || { echo "FAIL: wrong event id accepted"; exit 1; }
echo "PASS: wrong disaster_event_id refuse"

# Exact event id with supported ordinary DROP must pass require_supported.
psqlq -c "SELECT flashback_require_supported_drop_manifest($tid, $eid);" >/dev/null
echo "PASS: exact disaster_event_id admit for ordinary DROP"

# recover_plan must not invent a latest-manifest fallback when binding pending
# (simulate by checking plan carries matching dependency_manifest_id).
mid=$(printf '%s' "$plan" | jq -r '.dependency_manifest_id // empty')
[[ -n "$mid" && "$mid" != "null" ]] || {
    # pending is acceptable; missing-with-restorable is not
    [[ "$code" == "exact_manifest_pending" || "$code" == "exact_manifest_missing" ]] \
        || { echo "FAIL: restorable plan without exact manifest id code=$code"; exit 1; }
}
echo "PASS: plan exact-manifest contract ($code manifest_id=${mid:-none})"
echo "PASS: exact manifest matrix"
