#!/usr/bin/env bash
# Exact event-bound dependency manifest fail-closed regressions.
# Requires a live PG* cluster with pg_flashback installed.
set -Eeuo pipefail

PSQL_BIN="${PSQL_BIN:-psql}"
psqlq() { "$PSQL_BIN" -X -v ON_ERROR_STOP=1 -qAt "$@"; }

if [[ "${REQUIRE_LIVE:-0}" != "1" && -z "${PGDATABASE:-}" && -z "${PGHOST:-}" ]]; then
    echo "SKIP: set PG* / REQUIRE_LIVE=1 for live exact-manifest matrix" >&2
    exit 0
fi

cleanup() {
    psqlq -c "SELECT flashback_unprotect('public.em_exact');" >/dev/null 2>&1 || true
    psqlq -c "DROP TABLE IF EXISTS public.em_exact CASCADE;" >/dev/null 2>&1 || true
    psqlq -c "DROP VIEW IF EXISTS public.em_exact_v CASCADE;" >/dev/null 2>&1 || true
}
trap cleanup EXIT

psqlq <<'SQL'
DROP VIEW IF EXISTS public.em_exact_v CASCADE;
DROP TABLE IF EXISTS public.em_exact CASCADE;
CREATE TABLE public.em_exact(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    n text NOT NULL
);
INSERT INTO public.em_exact(n) VALUES ('a');
SELECT flashback_track('public.em_exact');
SQL

for _ in $(seq 1 120); do
    h=$(psqlq -c "SELECT flashback_lifecycle_health('public.em_exact');")
    [[ "$h" == "healthy" ]] && break
    sleep 0.25
done
[[ "$h" == "healthy" ]] || { echo "FAIL: not healthy"; exit 1; }

# flashback_list_lifecycles()->0 is whichever lifecycle happens to sort
# first across the whole database, not necessarily em_exact's — on a shared
# test cluster with other tracked tables that silently picks the wrong
# tracking_id. Resolve em_exact's own tracking_id directly instead.
tid=$(psqlq -c "SELECT tracking_id FROM flashback.tracked_tables WHERE is_active AND schema_name='public' AND table_name='em_exact';")

# Identity-less call must fail closed.
set +e
out=$(psqlq -c "SELECT flashback_require_supported_drop_manifest($tid);" 2>&1)
rc=$?
set -e
[[ $rc -ne 0 ]] || { echo "FAIL: identity-less call succeeded"; exit 1; }
printf '%s' "$out" | grep -qi 'exact DROP identity required' || {
    echo "FAIL: unexpected identity-less error: $out"; exit 1;
}
echo "PASS: identity-less refuse"

psqlq -c "DROP TABLE public.em_exact;"
for _ in $(seq 1 120); do
    st=$(psqlq -c "SELECT status FROM flashback_disaster_points('public.em_exact', interval '1 day') WHERE event_type='DROP' ORDER BY disaster_commit_lsn DESC LIMIT 1;")
    [[ "$st" == "restorable" || "$st" == "non_restorable" ]] && break
    sleep 0.25
done

plan=$(psqlq -c "SELECT flashback_recover_plan('public.em_exact', interval '1 day');")
code=$(printf '%s' "$plan" | jq -r '.code')
eid=$(printf '%s' "$plan" | jq -r '.disaster_event_id // empty')
[[ -n "$eid" && "$eid" != "null" ]] || { echo "FAIL: no disaster_event_id in plan code=$code"; echo "$plan"; exit 1; }

# Wrong event id must fail closed (not fall back to latest).
set +e
out=$(psqlq -c "SELECT flashback_require_supported_drop_manifest($tid, ($eid + 999999)::bigint);" 2>&1)
rc=$?
set -e
[[ $rc -ne 0 ]] || { echo "FAIL: wrong event id accepted"; exit 1; }
echo "PASS: wrong disaster_event_id refuse"

# Exact event id with supported ordinary DROP must pass require_supported.
# The exact manifest is bound asynchronously by
# flashback_bind_drop_dependency_manifests (worker-driven); a disaster_event_id
# appearing in flashback_recover_plan()'s output does not guarantee the bind
# has landed yet (that race is exactly what plan code=exact_manifest_pending
# communicates to CLI callers), so poll here the same way a real caller would.
admit_ok=0
for _ in $(seq 1 120); do
    # flashback_require_supported_drop_manifest() is STABLE and never binds on
    # its own; flashback_bind_drop_dependency_manifests() (worker-driven, also
    # what flashback_recover_plan() self-heals with) is the sole path that
    # resolves disaster_event_id onto the captured manifest row.
    psqlq -c "SELECT flashback_bind_drop_dependency_manifests();" >/dev/null
    set +e
    out=$(psqlq -c "SELECT flashback_require_supported_drop_manifest($tid, $eid);" 2>&1)
    rc=$?
    set -e
    [[ $rc -eq 0 ]] && { admit_ok=1; break; }
    printf '%s' "$out" | grep -qi 'no exact pre-DROP dependency manifest bound' || {
        echo "FAIL: exact disaster_event_id admit for ordinary DROP: $out"; exit 1;
    }
    sleep 0.25
done
[[ $admit_ok -eq 1 ]] || { echo "FAIL: exact manifest never bound within timeout: $out"; exit 1; }
echo "PASS: exact disaster_event_id admit for ordinary DROP"

# Explicit NULL disaster_event_id must refuse identically to the omitted case
# (no silent "any manifest for this tracking_id" fallback).
set +e
out=$(psqlq -c "SELECT flashback_require_supported_drop_manifest($tid, NULL::bigint);" 2>&1)
rc=$?
set -e
[[ $rc -ne 0 ]] || { echo "FAIL: explicit NULL disaster_event_id accepted"; exit 1; }
printf '%s' "$out" | grep -qi 'exact DROP identity required' || {
    echo "FAIL: unexpected explicit-NULL error: $out"; exit 1;
}
echo "PASS: explicit NULL disaster_event_id refuse"

# Transitional xid/lsn admit arms must be gone: the 4-arg legacy signature
# should no longer resolve to a function at all.
set +e
out=$(psqlq -c "SELECT flashback_require_supported_drop_manifest($tid, $eid, '0/0'::pg_lsn, 1::bigint);" 2>&1)
rc=$?
set -e
[[ $rc -ne 0 ]] || { echo "FAIL: legacy 4-arg xid/lsn signature unexpectedly resolved"; exit 1; }
printf '%s' "$out" | grep -qi 'does not exist' || {
    echo "FAIL: unexpected legacy-signature error: $out"; exit 1;
}
echo "PASS: legacy xid/lsn transitional signature removed"

# A real disaster_event_id must not admit for a different tracking_id: the
# manifest is bound to one lifecycle, never borrowed cross-lifecycle.
psqlq <<'SQL' >/dev/null
DROP TABLE IF EXISTS public.em_exact_cross CASCADE;
CREATE TABLE public.em_exact_cross(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, n text NOT NULL);
INSERT INTO public.em_exact_cross(n) VALUES ('a');
SELECT flashback_track('public.em_exact_cross');
SQL
for _ in $(seq 1 120); do
    h2=$(psqlq -c "SELECT flashback_lifecycle_health('public.em_exact_cross');")
    [[ "$h2" == "healthy" ]] && break
    sleep 0.25
done
[[ "$h2" == "healthy" ]] || { echo "FAIL: em_exact_cross not healthy"; exit 1; }
tid2=$(psqlq -c "SELECT tracking_id FROM flashback.tracked_tables WHERE table_name='em_exact_cross' ORDER BY tracked_since DESC LIMIT 1;")
set +e
out=$(psqlq -c "SELECT flashback_require_supported_drop_manifest($tid2, $eid);" 2>&1)
rc=$?
set -e
[[ $rc -ne 0 ]] || { echo "FAIL: cross-lifecycle disaster_event_id admitted"; exit 1; }
psqlq -c "SELECT flashback_unprotect('public.em_exact_cross');" >/dev/null 2>&1 || true
psqlq -c "DROP TABLE IF EXISTS public.em_exact_cross CASCADE;" >/dev/null 2>&1 || true
echo "PASS: cross-lifecycle disaster_event_id refuse"

# recover_plan must not invent a latest-manifest fallback when binding pending
# (simulate by checking plan carries matching dependency_manifest_id).
mid=$(printf '%s' "$plan" | jq -r '.dependency_manifest_id // empty')
[[ -n "$mid" && "$mid" != "null" ]] || {
    # pending is acceptable; missing-with-restorable is not
    [[ "$code" == "exact_manifest_pending" || "$code" == "exact_manifest_missing" ]] \
        || { echo "FAIL: restorable plan without exact manifest id code=$code"; exit 1; }
}
echo "PASS: plan exact-manifest contract ($code manifest_id=${mid:-none})"
echo "PASS: exact manifest matrix"
