#!/usr/bin/env bash
# Smoke a local_delta package archive for one PostgreSQL major.
# Usage:
#   ARCHIVE=... PG_CONFIG=... ./scripts/run_local_package_smoke.sh
# Or from inside an extracted archive:
#   ./scripts/run_local_package_smoke.sh

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARCHIVE="${ARCHIVE:-}"
PG_CONFIG="${PG_CONFIG:-$(command -v pg_config || true)}"
[[ -n "$PG_CONFIG" && -x "$PG_CONFIG" ]] || {
    echo "FAIL: pg_config required" >&2
    exit 1
}
PG_BIN="$(dirname "$PG_CONFIG")"
PG_MAJOR="$("$PG_CONFIG" --version | sed -n 's/.* \([0-9][0-9]*\)\..*/\1/p')"

WORKDIR="$(mktemp -d)"
cleanup() {
    if [[ -n "${PGDATA:-}" ]]; then
        "$PG_BIN/pg_ctl" -D "$PGDATA" stop -m immediate -w >/dev/null 2>&1 || true
    fi
    rm -rf "$WORKDIR"
}
trap cleanup EXIT

if [[ -n "$ARCHIVE" ]]; then
    tar -C "$WORKDIR" -xzf "$ARCHIVE"
    PKG="$(find "$WORKDIR" -maxdepth 1 -type d -name 'pg_flashback-*-linux' -print -quit)"
else
    # Assume we are already inside an extracted package, or ROOT is the package.
    if [[ -f "$ROOT/lib/pg_flashback.so" ]]; then
        PKG="$ROOT"
    else
        echo "FAIL: set ARCHIVE=path/to/pg_flashback-*.tar.gz" >&2
        exit 1
    fi
fi
[[ -n "$PKG" && -f "$PKG/lib/pg_flashback.so" ]]
test "$(cat "$PKG/PG_MAJOR")" = "$PG_MAJOR"
test "$(cat "$PKG/INSTALL_CONTRACT" 2>/dev/null || echo fresh-install-only)" = "fresh-install-only"

install -m 0755 "$PKG/lib/pg_flashback.so" "$("$PG_CONFIG" --pkglibdir)/pg_flashback.so"
install -m 0644 "$PKG"/share/extension/pg_flashback.control \
    "$PKG"/share/extension/pg_flashback--*.sql \
    "$("$PG_CONFIG" --sharedir)/extension/"
install -m 0755 "$PKG/bin/pg_flashback" "$WORKDIR/bin/pg_flashback"
export PATH="$WORKDIR/bin:$PATH"

PGDATA="$WORKDIR/data"
SOCKET="$WORKDIR/socket"
mkdir -p "$SOCKET"
PORT=$((55000 + PG_MAJOR))
"$PG_BIN/initdb" -D "$PGDATA" --locale=C.UTF-8 -A trust >/dev/null
cat >> "$PGDATA/postgresql.conf" <<EOF
shared_preload_libraries = 'pg_flashback'
wal_level = logical
max_worker_processes = 16
max_replication_slots = 8
max_wal_senders = 8
max_slot_wal_keep_size = '1GB'
pg_flashback.enabled = on
pg_flashback.capture_mode = wal
pg_flashback.target_databases = 'postgres'
pg_flashback.max_workers = 4
pg_flashback.local_max_snapshot_bytes = '512MB'
pg_flashback.local_max_restore_peak_bytes = '1GB'
pg_flashback.local_min_filesystem_bytes = '64MB'
pg_flashback.local_safety_reserve_bytes = '16MB'
EOF
"$PG_BIN/pg_ctl" -D "$PGDATA" -l "$PGDATA/postgresql.log" \
    -o "-p $PORT -k $SOCKET" start -w >/dev/null
export PGHOST="$SOCKET" PGPORT="$PORT" PGDATABASE=postgres PGUSER="$(whoami)"

psql -v ON_ERROR_STOP=1 -qAtc "CREATE EXTENSION pg_flashback;"
psql -v ON_ERROR_STOP=1 <<'SQL'
CREATE ROLE pgfb_operator LOGIN;
GRANT flashback_admin TO pgfb_operator;
SQL
export PGUSER=pgfb_operator

pg_flashback doctor >/dev/null
pg_flashback config recommend >/dev/null

psql -v ON_ERROR_STOP=1 <<'SQL'
CREATE TABLE public.package_smoke(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note text NOT NULL
);
INSERT INTO public.package_smoke(note) VALUES ('before'), ('keep');
SQL

pg_flashback protect public.package_smoke
psql -v ON_ERROR_STOP=1 -c "UPDATE public.package_smoke SET note='after' WHERE id=1;"
psql -v ON_ERROR_STOP=1 -c "DROP TABLE public.package_smoke;"
pg_flashback recover public.package_smoke --dry-run >/dev/null
pg_flashback recover public.package_smoke --yes --latest-drop

fp="$(psql -v ON_ERROR_STOP=1 -qAtc "SELECT count(*) FROM public.package_smoke WHERE note IN ('after','keep');")"
test "$fp" = "2"

tid="$(psql -v ON_ERROR_STOP=1 -qAtc "SELECT (flashback_list_lifecycles()->0->>'tracking_id');")"
pg_flashback unprotect public.package_smoke --yes
if [[ -n "$tid" && "$tid" != "null" ]]; then
  pg_flashback cleanup --tracking-id "$tid" --yes
fi
pg_flashback prepare-uninstall --yes

export PGUSER="$(whoami)"
psql -v ON_ERROR_STOP=1 -c "DROP EXTENSION pg_flashback;"
slots="$(psql -v ON_ERROR_STOP=1 -qAtc "SELECT count(*) FROM pg_replication_slots WHERE slot_name LIKE 'pg_flashback%';")"
test "$slots" = "0"

echo "PASS: local package smoke PG${PG_MAJOR}"
