-- Identity columns are catalog state, not ordinary nextval defaults. Prove
-- schema capture/recreation preserves generation mode and custom sequence
-- options before the exact-candidate DROP suite exercises the full LSN swap.
DO $tv$
DECLARE
    v_schema jsonb;
    v_always "char";
    v_default "char";
    v_options record;
    v_expected_state jsonb;
    v_actual_state jsonb;
    v_seq regclass;
BEGIN
    DROP TABLE IF EXISTS public.it_identity_schema CASCADE;
    CREATE TABLE public.it_identity_schema (
        id_always bigint GENERATED ALWAYS AS IDENTITY (
            START WITH 7 INCREMENT BY 3 MINVALUE 1 MAXVALUE 999999 CACHE 5 CYCLE
        ),
        id_default bigint GENERATED BY DEFAULT AS IDENTITY,
        payload text NOT NULL,
        PRIMARY KEY (id_always)
    );

    v_schema := flashback_collect_schema_def('public.it_identity_schema'::regclass);
    IF v_schema#>>'{columns,0,identity}' IS DISTINCT FROM 'a'
       OR v_schema#>>'{columns,1,identity}' IS DISTINCT FROM 'd'
    THEN
        RAISE EXCEPTION 'identity generation mode missing from captured schema: %', v_schema;
    END IF;

    PERFORM flashback_recreate_table_from_ddl(
        v_schema, 'pg_temp', 'it_identity_schema_shadow'
    );
    SELECT max(attidentity) FILTER (WHERE attname='id_always'),
           max(attidentity) FILTER (WHERE attname='id_default')
      INTO v_always, v_default
    FROM pg_attribute
    WHERE attrelid='pg_temp.it_identity_schema_shadow'::regclass
      AND attnum>0 AND NOT attisdropped;
    IF v_always IS DISTINCT FROM 'a' OR v_default IS DISTINCT FROM 'd' THEN
        RAISE EXCEPTION 'identity generation modes were not recreated: always=% default=%',
            v_always, v_default;
    END IF;

    SELECT s.seqstart, s.seqincrement, s.seqmin, s.seqmax, s.seqcache, s.seqcycle
      INTO v_options
    FROM pg_attribute a
    JOIN pg_depend d
      ON d.refobjid=a.attrelid AND d.refobjsubid=a.attnum
     AND d.classid='pg_class'::regclass AND d.deptype='i'
    JOIN pg_sequence s ON s.seqrelid=d.objid
    WHERE a.attrelid='pg_temp.it_identity_schema_shadow'::regclass
      AND a.attname='id_always';
    IF v_options.seqstart <> 7 OR v_options.seqincrement <> 3
       OR v_options.seqmin <> 1 OR v_options.seqmax <> 999999
       OR v_options.seqcache <> 5 OR NOT v_options.seqcycle
    THEN
        RAISE EXCEPTION 'identity sequence options were not recreated: %', v_options;
    END IF;

    INSERT INTO pg_temp.it_identity_schema_shadow(id_always,id_default,payload)
      OVERRIDING SYSTEM VALUE VALUES (100,200,'historical');
    IF NOT EXISTS (
        SELECT 1 FROM pg_temp.it_identity_schema_shadow
        WHERE id_always=100 AND id_default=200 AND payload='historical'
    ) THEN
        RAISE EXCEPTION 'identity shadow rejected explicit historical values';
    END IF;

    -- Expected state comes from table contents; actual state must come from
    -- the sequence relation itself.  Prove a wrong setval is observable
    -- rather than allowing both proof sides to derive the same value.
    INSERT INTO public.it_identity_schema(payload) VALUES ('state-proof');
    PERFORM setval(
        to_regclass(pg_get_serial_sequence(
            'public.it_identity_schema', 'id_always'
        )),
        (SELECT max(id_always) FROM public.it_identity_schema),
        true
    );
    PERFORM setval(
        to_regclass(pg_get_serial_sequence(
            'public.it_identity_schema', 'id_default'
        )),
        (SELECT max(id_default) FROM public.it_identity_schema),
        true
    );
    v_expected_state := flashback_expected_sequence_states(
        'public.it_identity_schema'::regclass, v_schema
    );
    v_actual_state := flashback_actual_sequence_states(
        'public.it_identity_schema'::regclass, v_schema
    );
    IF v_expected_state IS DISTINCT FROM v_actual_state THEN
        RAISE EXCEPTION 'healthy identity state proof disagrees: expected=% actual=%',
            v_expected_state, v_actual_state;
    END IF;
    v_seq := to_regclass(pg_get_serial_sequence(
        'public.it_identity_schema', 'id_always'
    ));
    PERFORM setval(v_seq, 500, true);
    v_actual_state := flashback_actual_sequence_states(
        'public.it_identity_schema'::regclass, v_schema
    );
    IF v_expected_state IS NOT DISTINCT FROM v_actual_state THEN
        RAISE EXCEPTION 'sequence-state verifier did not detect wrong live setval';
    END IF;

    DROP TABLE public.it_identity_schema CASCADE;
END;
$tv$;
